use crate::*;
use teaql_core::TeaqlEntity;

use teaql_provider_sqlite::SqliteProviderExt as _;

pub type DataServiceDialect = teaql_provider_sqlite::SqliteDialect;
pub type DataServiceMutationExecutor = teaql_provider_sqlite::SqliteMutationExecutor;
pub type DataServiceMutationError = teaql_provider_sqlite::MutationExecutorError;
pub type DataServiceIdGenerator = teaql_provider_sqlite::SqliteIdSpaceGenerator;
pub type DataServicePool = std::sync::Arc<std::sync::Mutex<rusqlite::Connection>>;
pub type DataServiceExecutor = ServiceRuntimeExecutor;
pub type ServiceRuntime = teaql_runtime::UserContext;

pub const DATABASE_URL_ENV: &str = "PLATFORM_MODULES_CORE_DATABASE_URL";
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServiceRuntimeConfig {
    pub database_url: String,
}

impl ServiceRuntimeConfig {
    pub fn from_env() -> Result<Self, ServiceRuntimeError> {
        Ok(Self {
            database_url: env_value(DATABASE_URL_ENV)?,
        })
    }
}

#[derive(Debug)]
pub enum ServiceRuntimeError {
    MissingEnv {
        name: &'static str,
        source: std::env::VarError,
    },
    ConnectionError(String),
    Rusqlite(rusqlite::Error),
    Runtime(teaql_runtime::RuntimeError),
}

impl std::fmt::Display for ServiceRuntimeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ServiceRuntimeError::MissingEnv { name, source } => {
                write!(f, "missing environment variable {name}: {source}")
            }
            ServiceRuntimeError::ConnectionError(err) => write!(f, "connection error: {err}"),
            ServiceRuntimeError::Rusqlite(err) => write!(f, "rusqlite error: {err}"),
            ServiceRuntimeError::Runtime(err) => write!(f, "runtime error: {err}"),
        }
    }
}

impl std::error::Error for ServiceRuntimeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ServiceRuntimeError::MissingEnv { source, .. } => Some(source),
            ServiceRuntimeError::ConnectionError(_) => None,
            ServiceRuntimeError::Rusqlite(err) => Some(err),
            ServiceRuntimeError::Runtime(err) => Some(err),
        }
    }
}

impl From<rusqlite::Error> for ServiceRuntimeError {
    fn from(err: rusqlite::Error) -> Self {
        ServiceRuntimeError::Rusqlite(err)
    }
}
impl From<teaql_runtime::RuntimeError> for ServiceRuntimeError {
    fn from(err: teaql_runtime::RuntimeError) -> Self {
        ServiceRuntimeError::Runtime(err)
    }
}

#[derive(Clone)]
pub struct LocalSchemaProvider;

impl teaql_data_service::SchemaProvider for LocalSchemaProvider {
    fn get_entity(&self, name: &str) -> Option<std::sync::Arc<teaql_core::EntityDescriptor>> {
        match name {
            "Address" => Some(std::sync::Arc::new(crate::Address::entity_descriptor())),
            "MovingEvent" => Some(std::sync::Arc::new(crate::MovingEvent::entity_descriptor())),
            "Route" => Some(std::sync::Arc::new(crate::Route::entity_descriptor())),
            "TimeSlot" => Some(std::sync::Arc::new(crate::TimeSlot::entity_descriptor())),
            "FulfillmentEvent" => Some(std::sync::Arc::new(crate::FulfillmentEvent::entity_descriptor())),
            "Staff" => Some(std::sync::Arc::new(crate::Staff::entity_descriptor())),
            "JobAssignment" => Some(std::sync::Arc::new(crate::JobAssignment::entity_descriptor())),
            "WorkedHours" => Some(std::sync::Arc::new(crate::WorkedHours::entity_descriptor())),
            "Payroll" => Some(std::sync::Arc::new(crate::Payroll::entity_descriptor())),
            "Bonus" => Some(std::sync::Arc::new(crate::Bonus::entity_descriptor())),
            "LeaveTracking" => Some(std::sync::Arc::new(crate::LeaveTracking::entity_descriptor())),
            "PrivateCustomer" => Some(std::sync::Arc::new(crate::PrivateCustomer::entity_descriptor())),
            "CorporateCustomer" => Some(std::sync::Arc::new(crate::CorporateCustomer::entity_descriptor())),
            "CustomerContact" => Some(std::sync::Arc::new(crate::CustomerContact::entity_descriptor())),
            "MovingService" => Some(std::sync::Arc::new(crate::MovingService::entity_descriptor())),
            "CleaningService" => Some(std::sync::Arc::new(crate::CleaningService::entity_descriptor())),
            "Campaign" => Some(std::sync::Arc::new(crate::Campaign::entity_descriptor())),
            "DiscountCode" => Some(std::sync::Arc::new(crate::DiscountCode::entity_descriptor())),
            "Lead" => Some(std::sync::Arc::new(crate::Lead::entity_descriptor())),
            "ConversionMetric" => Some(std::sync::Arc::new(crate::ConversionMetric::entity_descriptor())),
            "Payment" => Some(std::sync::Arc::new(crate::Payment::entity_descriptor())),
            "Invoice" => Some(std::sync::Arc::new(crate::Invoice::entity_descriptor())),
            "Expense" => Some(std::sync::Arc::new(crate::Expense::entity_descriptor())),
            "VatRecord" => Some(std::sync::Arc::new(crate::VatRecord::entity_descriptor())),
            "FinancialSummary" => Some(std::sync::Arc::new(crate::FinancialSummary::entity_descriptor())),
            "Vehicle" => Some(std::sync::Arc::new(crate::Vehicle::entity_descriptor())),
            "Equipment" => Some(std::sync::Arc::new(crate::Equipment::entity_descriptor())),
            "Consumable" => Some(std::sync::Arc::new(crate::Consumable::entity_descriptor())),
            "User" => Some(std::sync::Arc::new(crate::User::entity_descriptor())),
            "Role" => Some(std::sync::Arc::new(crate::Role::entity_descriptor())),
            "Permission" => Some(std::sync::Arc::new(crate::Permission::entity_descriptor())),
            "UserRole" => Some(std::sync::Arc::new(crate::UserRole::entity_descriptor())),
            "RolePermission" => Some(std::sync::Arc::new(crate::RolePermission::entity_descriptor())),
            "AuthenticationLog" => Some(std::sync::Arc::new(crate::AuthenticationLog::entity_descriptor())),
            "ActivityLog" => Some(std::sync::Arc::new(crate::ActivityLog::entity_descriptor())),
            "Notification" => Some(std::sync::Arc::new(crate::Notification::entity_descriptor())),
            "ApiEndpoint" => Some(std::sync::Arc::new(crate::ApiEndpoint::entity_descriptor())),
            "Webhook" => Some(std::sync::Arc::new(crate::Webhook::entity_descriptor())),
            _ => None,
        }
    }
}

#[derive(Clone)]
pub struct ServiceRuntimeExecutor {
    inner: teaql_sql::SqlDataServiceExecutor<
        DataServiceDialect,
        DataServiceMutationExecutor,
        LocalSchemaProvider
    >,
}

impl ServiceRuntimeExecutor {
    pub fn new(inner: DataServiceMutationExecutor) -> Self {
        Self {
            inner: teaql_sql::SqlDataServiceExecutor::new(
                DataServiceDialect::default(),
                inner,
                LocalSchemaProvider
            ),
        }
    }

}

impl teaql_data_service::DataServiceExecutor for ServiceRuntimeExecutor {
    type Error = teaql_sql::SqlExecutorError<DataServiceMutationError>;
    fn capabilities(&self) -> teaql_data_service::DataServiceCapabilities {
        teaql_data_service::DataServiceExecutor::capabilities(&self.inner)
    }
}

impl teaql_data_service::QueryExecutor for ServiceRuntimeExecutor {
    async fn query(&self, request: teaql_data_service::QueryRequest) -> Result<teaql_data_service::QueryResult, Self::Error> {
        teaql_data_service::QueryExecutor::query(&self.inner, request).await
    }
}

impl teaql_data_service::StreamQueryExecutor for ServiceRuntimeExecutor {
    async fn query_stream(&self, request: teaql_data_service::QueryRequest, chunk_size: usize) -> Result<Vec<teaql_data_service::StreamChunk>, Self::Error> {
        teaql_data_service::StreamQueryExecutor::query_stream(&self.inner, request, chunk_size).await
    }
}

impl teaql_data_service::MutationExecutor for ServiceRuntimeExecutor {
    async fn mutate(&self, request: teaql_data_service::MutationRequest) -> Result<teaql_data_service::MutationResult, Self::Error> {
        teaql_data_service::MutationExecutor::mutate(&self.inner, request).await
    }
}

impl teaql_data_service::TransactionExecutor for ServiceRuntimeExecutor {
    type Tx<'a> = teaql_sql::SqlDataServiceTransaction<'a, DataServiceDialect, <DataServiceMutationExecutor as teaql_sql::SqlTransactionTransport>::Tx<'a>, LocalSchemaProvider> where Self: 'a;

    async fn begin(&self) -> Result<Self::Tx<'_ >, Self::Error> {
        teaql_data_service::TransactionExecutor::begin(&self.inner).await
    }
}

pub async fn service_runtime_from_env() -> Result<ServiceRuntime, ServiceRuntimeError> {
    service_runtime(ServiceRuntimeConfig::from_env()?).await
}

pub async fn service_runtime(config: ServiceRuntimeConfig) -> Result<ServiceRuntime, ServiceRuntimeError> {
    let pool = connect_data_service_pool(&config).await?;
    service_runtime_from_pool(pool).await
}

pub async fn service_runtime_from_pool(pool: DataServicePool) -> Result<ServiceRuntime, ServiceRuntimeError> {
    let mutation_executor = DataServiceMutationExecutor::new(pool);
    let id_generator = DataServiceIdGenerator::from_executor(mutation_executor.clone());let mut context = module_with_behaviors_and_checkers().into_context();
    context.set_internal_id_generator(id_generator);
    context.use_sqlite_provider(mutation_executor.clone());
    let executor = ServiceRuntimeExecutor::new(mutation_executor);
    context.register_executor(executor.clone());
    context.insert_resource(executor);

    // 自动加载 Zero-Code 审计配置与 Schema 模式
    let env_config = teaql_tool_core::audit_config_from_env(&[
        "address_data", "moving_event_data", "route_data", "time_slot_data", "fulfillment_event_data", "staff_data", "job_assignment_data", "worked_hours_data", "payroll_data", "bonus_data", "leave_tracking_data", "private_customer_data", "corporate_customer_data", "customer_contact_data", "moving_service_data", "cleaning_service_data", "campaign_data", "discount_code_data", "lead_data", "conversion_metric_data", "payment_data", "invoice_data", "expense_data", "vat_record_data", "financial_summary_data", "vehicle_data", "equipment_data", "consumable_data", "user_data", "role_data", "permission_data", "user_role_data", "role_permission_data", "authentication_log_data", "activity_log_data", "notification_data", "api_endpoint_data", "webhook_data"
    ]);
    let schema_mode = env_config.schema_mode;
    context.insert_resource(env_config.config.clone());
    context.insert_resource(env_config);

    match schema_mode {
        teaql_tool_core::SchemaMode::Execute => {
            context.ensure_schema().await?;
        }
        teaql_tool_core::SchemaMode::DryRun => {
            // DryRun: 目前等效于验证
            context.ensure_schema().await?;
        }
        teaql_tool_core::SchemaMode::Verify => {
            context.ensure_schema().await?;
        }
    }

    Ok(context)
}



fn env_value(name: &'static str) -> Result<String, ServiceRuntimeError> {
    std::env::var(name).map_err(|source| ServiceRuntimeError::MissingEnv { name, source })
}

async fn connect_data_service_pool(config: &ServiceRuntimeConfig) -> Result<DataServicePool, ServiceRuntimeError> {
    let url = &config.database_url;
    let sanitized_url = if url.starts_with("sqlite:") { url.strip_prefix("sqlite:").unwrap().trim_start_matches("//") } else { url };
    let pure_file_path = sanitized_url.split('?').next().unwrap_or(sanitized_url);
    let path = std::path::Path::new(pure_file_path);
    if let Some(parent) = path.parent() { if !parent.as_os_str().is_empty() { std::fs::create_dir_all(parent).map_err(|e| ServiceRuntimeError::ConnectionError(e.to_string()))?; } }
    Ok(std::sync::Arc::new(std::sync::Mutex::new(rusqlite::Connection::open(pure_file_path).map_err(|e| ServiceRuntimeError::ConnectionError(e.to_string()))?)))
}

pub fn repository_registry() -> teaql_runtime::InMemoryEntityRegistry {
    teaql_runtime::InMemoryEntityRegistry::new()
        .with_entity("Address")
        .with_entity("MovingEvent")
        .with_entity("Route")
        .with_entity("TimeSlot")
        .with_entity("FulfillmentEvent")
        .with_entity("Staff")
        .with_entity("JobAssignment")
        .with_entity("WorkedHours")
        .with_entity("Payroll")
        .with_entity("Bonus")
        .with_entity("LeaveTracking")
        .with_entity("PrivateCustomer")
        .with_entity("CorporateCustomer")
        .with_entity("CustomerContact")
        .with_entity("MovingService")
        .with_entity("CleaningService")
        .with_entity("Campaign")
        .with_entity("DiscountCode")
        .with_entity("Lead")
        .with_entity("ConversionMetric")
        .with_entity("Payment")
        .with_entity("Invoice")
        .with_entity("Expense")
        .with_entity("VatRecord")
        .with_entity("FinancialSummary")
        .with_entity("Vehicle")
        .with_entity("Equipment")
        .with_entity("Consumable")
        .with_entity("User")
        .with_entity("Role")
        .with_entity("Permission")
        .with_entity("UserRole")
        .with_entity("RolePermission")
        .with_entity("AuthenticationLog")
        .with_entity("ActivityLog")
        .with_entity("Notification")
        .with_entity("ApiEndpoint")
        .with_entity("Webhook")
}

pub fn behavior_registry() -> teaql_runtime::InMemoryEntityDataServiceBehaviorRegistry {
    teaql_runtime::InMemoryEntityDataServiceBehaviorRegistry::new()
        .with_behavior("Address", AddressBehavior::default())
        .with_behavior("MovingEvent", MovingEventBehavior::default())
        .with_behavior("Route", RouteBehavior::default())
        .with_behavior("TimeSlot", TimeSlotBehavior::default())
        .with_behavior("FulfillmentEvent", FulfillmentEventBehavior::default())
        .with_behavior("Staff", StaffBehavior::default())
        .with_behavior("JobAssignment", JobAssignmentBehavior::default())
        .with_behavior("WorkedHours", WorkedHoursBehavior::default())
        .with_behavior("Payroll", PayrollBehavior::default())
        .with_behavior("Bonus", BonusBehavior::default())
        .with_behavior("LeaveTracking", LeaveTrackingBehavior::default())
        .with_behavior("PrivateCustomer", PrivateCustomerBehavior::default())
        .with_behavior("CorporateCustomer", CorporateCustomerBehavior::default())
        .with_behavior("CustomerContact", CustomerContactBehavior::default())
        .with_behavior("MovingService", MovingServiceBehavior::default())
        .with_behavior("CleaningService", CleaningServiceBehavior::default())
        .with_behavior("Campaign", CampaignBehavior::default())
        .with_behavior("DiscountCode", DiscountCodeBehavior::default())
        .with_behavior("Lead", LeadBehavior::default())
        .with_behavior("ConversionMetric", ConversionMetricBehavior::default())
        .with_behavior("Payment", PaymentBehavior::default())
        .with_behavior("Invoice", InvoiceBehavior::default())
        .with_behavior("Expense", ExpenseBehavior::default())
        .with_behavior("VatRecord", VatRecordBehavior::default())
        .with_behavior("FinancialSummary", FinancialSummaryBehavior::default())
        .with_behavior("Vehicle", VehicleBehavior::default())
        .with_behavior("Equipment", EquipmentBehavior::default())
        .with_behavior("Consumable", ConsumableBehavior::default())
        .with_behavior("User", UserBehavior::default())
        .with_behavior("Role", RoleBehavior::default())
        .with_behavior("Permission", PermissionBehavior::default())
        .with_behavior("UserRole", UserRoleBehavior::default())
        .with_behavior("RolePermission", RolePermissionBehavior::default())
        .with_behavior("AuthenticationLog", AuthenticationLogBehavior::default())
        .with_behavior("ActivityLog", ActivityLogBehavior::default())
        .with_behavior("Notification", NotificationBehavior::default())
        .with_behavior("ApiEndpoint", ApiEndpointBehavior::default())
        .with_behavior("Webhook", WebhookBehavior::default())
}

pub fn checker_registry() -> teaql_runtime::InMemoryCheckerRegistry {
    teaql_runtime::InMemoryCheckerRegistry::new()
        .with_checker(teaql_runtime::TypedEntityChecker::<Address, _>::new(AddressChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<MovingEvent, _>::new(MovingEventChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Route, _>::new(RouteChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<TimeSlot, _>::new(TimeSlotChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Staff, _>::new(StaffChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Payroll, _>::new(PayrollChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Bonus, _>::new(BonusChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<LeaveTracking, _>::new(LeaveTrackingChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<PrivateCustomer, _>::new(PrivateCustomerChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CorporateCustomer, _>::new(CorporateCustomerChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CustomerContact, _>::new(CustomerContactChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<MovingService, _>::new(MovingServiceChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CleaningService, _>::new(CleaningServiceChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Campaign, _>::new(CampaignChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<DiscountCode, _>::new(DiscountCodeChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Lead, _>::new(LeadChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ConversionMetric, _>::new(ConversionMetricChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Payment, _>::new(PaymentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Invoice, _>::new(InvoiceChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Expense, _>::new(ExpenseChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<VatRecord, _>::new(VatRecordChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<FinancialSummary, _>::new(FinancialSummaryChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Vehicle, _>::new(VehicleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Equipment, _>::new(EquipmentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Consumable, _>::new(ConsumableChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<User, _>::new(UserChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Role, _>::new(RoleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Permission, _>::new(PermissionChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<RolePermission, _>::new(RolePermissionChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<AuthenticationLog, _>::new(AuthenticationLogChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ActivityLog, _>::new(ActivityLogChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Notification, _>::new(NotificationChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ApiEndpoint, _>::new(ApiEndpointChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<Webhook, _>::new(WebhookChecker::default()))
}

pub fn module() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity::<Address>()
        .entity::<MovingEvent>()
        .entity::<Route>()
        .entity::<TimeSlot>()
        .entity::<FulfillmentEvent>()
        .entity::<Staff>()
        .entity::<JobAssignment>()
        .entity::<WorkedHours>()
        .entity::<Payroll>()
        .entity::<Bonus>()
        .entity::<LeaveTracking>()
        .entity::<PrivateCustomer>()
        .entity::<CorporateCustomer>()
        .entity::<CustomerContact>()
        .entity::<MovingService>()
        .entity::<CleaningService>()
        .entity::<Campaign>()
        .entity::<DiscountCode>()
        .entity::<Lead>()
        .entity::<ConversionMetric>()
        .entity::<Payment>()
        .entity::<Invoice>()
        .entity::<Expense>()
        .entity::<VatRecord>()
        .entity::<FinancialSummary>()
        .entity::<Vehicle>()
        .entity::<Equipment>()
        .entity::<Consumable>()
        .entity::<User>()
        .entity::<Role>()
        .entity::<Permission>()
        .entity::<UserRole>()
        .entity::<RolePermission>()
        .entity::<AuthenticationLog>()
        .entity::<ActivityLog>()
        .entity::<Notification>()
        .entity::<ApiEndpoint>()
        .entity::<Webhook>()
        .initial_graph(teaql_runtime::GraphNode::new("Address")
            .value("id", 1_u64)
            .value("street", "123 Main St")
            .value("city", "New York")
            .value("state", "NY")
            .value("postal_code", 10001_i64)
            .value("country", "USA")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Staff")
            .value("id", 1_u64)
            .value("employee_id", "STF001")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@fastmovers.com")
            .value("phone", "+1234567890")
            .value("hire_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("job_title", "Driver")
            .value("department", "department()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("PrivateCustomer")
            .value("id", 1_u64)
            .value("name", "Private Customer")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("address", "123 Main St")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CorporateCustomer")
            .value("id", 1_u64)
            .value("name", "Corporate Customer")
            .value("company_name", "Acme Corp")
            .value("tax_id", "TAX123456")
            .value("contact_person", "Jane Smith")
            .value("email", "jane.smith@acme.com")
            .value("phone", "+1234567891")
            .value("address", "456 Business Ave")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MovingService")
            .value("id", 1_u64)
            .value("name", "Standard Moving")
            .value("service_code", "MOV-STD")
            .value("base_price", "150.00")
            .value("description", "Standard household moving service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CleaningService")
            .value("id", 1_u64)
            .value("name", "Deep Cleaning")
            .value("service_code", "CLN-DP")
            .value("base_price", "80.00")
            .value("description", "Comprehensive deep cleaning service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Campaign")
            .value("id", 1_u64)
            .value("name", "Summer Move Promotion")
            .value("start_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("end_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("budget", "10000.00")
            .value("target_audience", "Residential")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("DiscountCode")
            .value("id", 1_u64)
            .value("code", "SUMMER10")
            .value("discount_percent", "10.00")
            .value("usage_limit", 500_i64)
            .value("used_count", 0_i64)
            .value("valid_from", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("valid_to", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Lead")
            .value("id", 1_u64)
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("source", "Online Ad")
            .value("status", "New")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Invoice")
            .value("id", 1_u64)
            .value("invoice_number", "INV-2024-001")
            .value("total_amount", "300.00")
            .value("tax_amount", "50.00")
            .value("status", "Sent")
            .value("customer", "customer()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Expense")
            .value("id", 1_u64)
            .value("description", "Fuel for truck")
            .value("amount", "75.50")
            .value("expense_type", "Fuel")
            .value("date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("VatRecord")
            .value("id", 1_u64)
            .value("vat_amount", "40.00")
            .value("tax_period", "Q1 2024")
            .value("filing_status", "Filed")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("FinancialSummary")
            .value("id", 1_u64)
            .value("period", "Monthly")
            .value("revenue", "5000.00")
            .value("expenses", "3000.00")
            .value("net_profit", "2000.00")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Vehicle")
            .value("id", 1_u64)
            .value("license_plate", "ABC123")
            .value("vehicle_type", "Truck")
            .value("capacity_kg", "5000.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("status", "Active")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Equipment")
            .value("id", 1_u64)
            .value("name", "Dolly")
            .value("equipment_type", "Moving Equipment")
            .value("purchase_cost", "150.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("condition", "Good")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Consumable")
            .value("id", 1_u64)
            .value("name", "Moving Blanket")
            .value("item_type", "Packing Material")
            .value("unit_cost", "8.50")
            .value("quantity_in_stock", 200_i64)
            .value("reorder_level", 50_i64)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("User")
            .value("id", 1_u64)
            .value("username", "john_doe")
            .value("email", "john@example.com")
            .value("password_hash", "hashed_password_123")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Role")
            .value("id", 1_u64)
            .value("name", "admin")
            .value("description", "System administrator")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Permission")
            .value("id", 1_u64)
            .value("name", "manage_users")
            .value("description", "Can manage user accounts")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("ApiEndpoint")
            .value("id", 1_u64)
            .value("path", "/api/v1/users")
            .value("method", "GET")
            .value("description", "Get user list")
            .value("version", "v1")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now()))
        .initial_graph(teaql_runtime::GraphNode::new("Webhook")
            .value("id", 1_u64)
            .value("url", "//example.com/webhook")
            .value("event_type", "invoice_paid")
            .value("secret_key", "webhook_secret_123")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
}

pub fn module_with_checkers() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity::<Address>()
        .checker(teaql_runtime::TypedEntityChecker::<Address, _>::new(AddressChecker::default()))
        .entity::<MovingEvent>()
        .checker(teaql_runtime::TypedEntityChecker::<MovingEvent, _>::new(MovingEventChecker::default()))
        .entity::<Route>()
        .checker(teaql_runtime::TypedEntityChecker::<Route, _>::new(RouteChecker::default()))
        .entity::<TimeSlot>()
        .checker(teaql_runtime::TypedEntityChecker::<TimeSlot, _>::new(TimeSlotChecker::default()))
        .entity::<FulfillmentEvent>()
        .checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .entity::<Staff>()
        .checker(teaql_runtime::TypedEntityChecker::<Staff, _>::new(StaffChecker::default()))
        .entity::<JobAssignment>()
        .checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .entity::<WorkedHours>()
        .checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .entity::<Payroll>()
        .checker(teaql_runtime::TypedEntityChecker::<Payroll, _>::new(PayrollChecker::default()))
        .entity::<Bonus>()
        .checker(teaql_runtime::TypedEntityChecker::<Bonus, _>::new(BonusChecker::default()))
        .entity::<LeaveTracking>()
        .checker(teaql_runtime::TypedEntityChecker::<LeaveTracking, _>::new(LeaveTrackingChecker::default()))
        .entity::<PrivateCustomer>()
        .checker(teaql_runtime::TypedEntityChecker::<PrivateCustomer, _>::new(PrivateCustomerChecker::default()))
        .entity::<CorporateCustomer>()
        .checker(teaql_runtime::TypedEntityChecker::<CorporateCustomer, _>::new(CorporateCustomerChecker::default()))
        .entity::<CustomerContact>()
        .checker(teaql_runtime::TypedEntityChecker::<CustomerContact, _>::new(CustomerContactChecker::default()))
        .entity::<MovingService>()
        .checker(teaql_runtime::TypedEntityChecker::<MovingService, _>::new(MovingServiceChecker::default()))
        .entity::<CleaningService>()
        .checker(teaql_runtime::TypedEntityChecker::<CleaningService, _>::new(CleaningServiceChecker::default()))
        .entity::<Campaign>()
        .checker(teaql_runtime::TypedEntityChecker::<Campaign, _>::new(CampaignChecker::default()))
        .entity::<DiscountCode>()
        .checker(teaql_runtime::TypedEntityChecker::<DiscountCode, _>::new(DiscountCodeChecker::default()))
        .entity::<Lead>()
        .checker(teaql_runtime::TypedEntityChecker::<Lead, _>::new(LeadChecker::default()))
        .entity::<ConversionMetric>()
        .checker(teaql_runtime::TypedEntityChecker::<ConversionMetric, _>::new(ConversionMetricChecker::default()))
        .entity::<Payment>()
        .checker(teaql_runtime::TypedEntityChecker::<Payment, _>::new(PaymentChecker::default()))
        .entity::<Invoice>()
        .checker(teaql_runtime::TypedEntityChecker::<Invoice, _>::new(InvoiceChecker::default()))
        .entity::<Expense>()
        .checker(teaql_runtime::TypedEntityChecker::<Expense, _>::new(ExpenseChecker::default()))
        .entity::<VatRecord>()
        .checker(teaql_runtime::TypedEntityChecker::<VatRecord, _>::new(VatRecordChecker::default()))
        .entity::<FinancialSummary>()
        .checker(teaql_runtime::TypedEntityChecker::<FinancialSummary, _>::new(FinancialSummaryChecker::default()))
        .entity::<Vehicle>()
        .checker(teaql_runtime::TypedEntityChecker::<Vehicle, _>::new(VehicleChecker::default()))
        .entity::<Equipment>()
        .checker(teaql_runtime::TypedEntityChecker::<Equipment, _>::new(EquipmentChecker::default()))
        .entity::<Consumable>()
        .checker(teaql_runtime::TypedEntityChecker::<Consumable, _>::new(ConsumableChecker::default()))
        .entity::<User>()
        .checker(teaql_runtime::TypedEntityChecker::<User, _>::new(UserChecker::default()))
        .entity::<Role>()
        .checker(teaql_runtime::TypedEntityChecker::<Role, _>::new(RoleChecker::default()))
        .entity::<Permission>()
        .checker(teaql_runtime::TypedEntityChecker::<Permission, _>::new(PermissionChecker::default()))
        .entity::<UserRole>()
        .checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .entity::<RolePermission>()
        .checker(teaql_runtime::TypedEntityChecker::<RolePermission, _>::new(RolePermissionChecker::default()))
        .entity::<AuthenticationLog>()
        .checker(teaql_runtime::TypedEntityChecker::<AuthenticationLog, _>::new(AuthenticationLogChecker::default()))
        .entity::<ActivityLog>()
        .checker(teaql_runtime::TypedEntityChecker::<ActivityLog, _>::new(ActivityLogChecker::default()))
        .entity::<Notification>()
        .checker(teaql_runtime::TypedEntityChecker::<Notification, _>::new(NotificationChecker::default()))
        .entity::<ApiEndpoint>()
        .checker(teaql_runtime::TypedEntityChecker::<ApiEndpoint, _>::new(ApiEndpointChecker::default()))
        .entity::<Webhook>()
        .checker(teaql_runtime::TypedEntityChecker::<Webhook, _>::new(WebhookChecker::default()))
        .initial_graph(teaql_runtime::GraphNode::new("Address")
            .value("id", 1_u64)
            .value("street", "123 Main St")
            .value("city", "New York")
            .value("state", "NY")
            .value("postal_code", 10001_i64)
            .value("country", "USA")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Staff")
            .value("id", 1_u64)
            .value("employee_id", "STF001")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@fastmovers.com")
            .value("phone", "+1234567890")
            .value("hire_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("job_title", "Driver")
            .value("department", "department()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("PrivateCustomer")
            .value("id", 1_u64)
            .value("name", "Private Customer")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("address", "123 Main St")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CorporateCustomer")
            .value("id", 1_u64)
            .value("name", "Corporate Customer")
            .value("company_name", "Acme Corp")
            .value("tax_id", "TAX123456")
            .value("contact_person", "Jane Smith")
            .value("email", "jane.smith@acme.com")
            .value("phone", "+1234567891")
            .value("address", "456 Business Ave")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MovingService")
            .value("id", 1_u64)
            .value("name", "Standard Moving")
            .value("service_code", "MOV-STD")
            .value("base_price", "150.00")
            .value("description", "Standard household moving service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CleaningService")
            .value("id", 1_u64)
            .value("name", "Deep Cleaning")
            .value("service_code", "CLN-DP")
            .value("base_price", "80.00")
            .value("description", "Comprehensive deep cleaning service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Campaign")
            .value("id", 1_u64)
            .value("name", "Summer Move Promotion")
            .value("start_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("end_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("budget", "10000.00")
            .value("target_audience", "Residential")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("DiscountCode")
            .value("id", 1_u64)
            .value("code", "SUMMER10")
            .value("discount_percent", "10.00")
            .value("usage_limit", 500_i64)
            .value("used_count", 0_i64)
            .value("valid_from", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("valid_to", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Lead")
            .value("id", 1_u64)
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("source", "Online Ad")
            .value("status", "New")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Invoice")
            .value("id", 1_u64)
            .value("invoice_number", "INV-2024-001")
            .value("total_amount", "300.00")
            .value("tax_amount", "50.00")
            .value("status", "Sent")
            .value("customer", "customer()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Expense")
            .value("id", 1_u64)
            .value("description", "Fuel for truck")
            .value("amount", "75.50")
            .value("expense_type", "Fuel")
            .value("date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("VatRecord")
            .value("id", 1_u64)
            .value("vat_amount", "40.00")
            .value("tax_period", "Q1 2024")
            .value("filing_status", "Filed")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("FinancialSummary")
            .value("id", 1_u64)
            .value("period", "Monthly")
            .value("revenue", "5000.00")
            .value("expenses", "3000.00")
            .value("net_profit", "2000.00")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Vehicle")
            .value("id", 1_u64)
            .value("license_plate", "ABC123")
            .value("vehicle_type", "Truck")
            .value("capacity_kg", "5000.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("status", "Active")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Equipment")
            .value("id", 1_u64)
            .value("name", "Dolly")
            .value("equipment_type", "Moving Equipment")
            .value("purchase_cost", "150.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("condition", "Good")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Consumable")
            .value("id", 1_u64)
            .value("name", "Moving Blanket")
            .value("item_type", "Packing Material")
            .value("unit_cost", "8.50")
            .value("quantity_in_stock", 200_i64)
            .value("reorder_level", 50_i64)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("User")
            .value("id", 1_u64)
            .value("username", "john_doe")
            .value("email", "john@example.com")
            .value("password_hash", "hashed_password_123")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Role")
            .value("id", 1_u64)
            .value("name", "admin")
            .value("description", "System administrator")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Permission")
            .value("id", 1_u64)
            .value("name", "manage_users")
            .value("description", "Can manage user accounts")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("ApiEndpoint")
            .value("id", 1_u64)
            .value("path", "/api/v1/users")
            .value("method", "GET")
            .value("description", "Get user list")
            .value("version", "v1")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now()))
        .initial_graph(teaql_runtime::GraphNode::new("Webhook")
            .value("id", 1_u64)
            .value("url", "//example.com/webhook")
            .value("event_type", "invoice_paid")
            .value("secret_key", "webhook_secret_123")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
}

pub fn module_with_behaviors() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity_with_behavior::<Address, _>(AddressBehavior::default())
        .entity_with_behavior::<MovingEvent, _>(MovingEventBehavior::default())
        .entity_with_behavior::<Route, _>(RouteBehavior::default())
        .entity_with_behavior::<TimeSlot, _>(TimeSlotBehavior::default())
        .entity_with_behavior::<FulfillmentEvent, _>(FulfillmentEventBehavior::default())
        .entity_with_behavior::<Staff, _>(StaffBehavior::default())
        .entity_with_behavior::<JobAssignment, _>(JobAssignmentBehavior::default())
        .entity_with_behavior::<WorkedHours, _>(WorkedHoursBehavior::default())
        .entity_with_behavior::<Payroll, _>(PayrollBehavior::default())
        .entity_with_behavior::<Bonus, _>(BonusBehavior::default())
        .entity_with_behavior::<LeaveTracking, _>(LeaveTrackingBehavior::default())
        .entity_with_behavior::<PrivateCustomer, _>(PrivateCustomerBehavior::default())
        .entity_with_behavior::<CorporateCustomer, _>(CorporateCustomerBehavior::default())
        .entity_with_behavior::<CustomerContact, _>(CustomerContactBehavior::default())
        .entity_with_behavior::<MovingService, _>(MovingServiceBehavior::default())
        .entity_with_behavior::<CleaningService, _>(CleaningServiceBehavior::default())
        .entity_with_behavior::<Campaign, _>(CampaignBehavior::default())
        .entity_with_behavior::<DiscountCode, _>(DiscountCodeBehavior::default())
        .entity_with_behavior::<Lead, _>(LeadBehavior::default())
        .entity_with_behavior::<ConversionMetric, _>(ConversionMetricBehavior::default())
        .entity_with_behavior::<Payment, _>(PaymentBehavior::default())
        .entity_with_behavior::<Invoice, _>(InvoiceBehavior::default())
        .entity_with_behavior::<Expense, _>(ExpenseBehavior::default())
        .entity_with_behavior::<VatRecord, _>(VatRecordBehavior::default())
        .entity_with_behavior::<FinancialSummary, _>(FinancialSummaryBehavior::default())
        .entity_with_behavior::<Vehicle, _>(VehicleBehavior::default())
        .entity_with_behavior::<Equipment, _>(EquipmentBehavior::default())
        .entity_with_behavior::<Consumable, _>(ConsumableBehavior::default())
        .entity_with_behavior::<User, _>(UserBehavior::default())
        .entity_with_behavior::<Role, _>(RoleBehavior::default())
        .entity_with_behavior::<Permission, _>(PermissionBehavior::default())
        .entity_with_behavior::<UserRole, _>(UserRoleBehavior::default())
        .entity_with_behavior::<RolePermission, _>(RolePermissionBehavior::default())
        .entity_with_behavior::<AuthenticationLog, _>(AuthenticationLogBehavior::default())
        .entity_with_behavior::<ActivityLog, _>(ActivityLogBehavior::default())
        .entity_with_behavior::<Notification, _>(NotificationBehavior::default())
        .entity_with_behavior::<ApiEndpoint, _>(ApiEndpointBehavior::default())
        .entity_with_behavior::<Webhook, _>(WebhookBehavior::default())
        .initial_graph(teaql_runtime::GraphNode::new("Address")
            .value("id", 1_u64)
            .value("street", "123 Main St")
            .value("city", "New York")
            .value("state", "NY")
            .value("postal_code", 10001_i64)
            .value("country", "USA")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Staff")
            .value("id", 1_u64)
            .value("employee_id", "STF001")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@fastmovers.com")
            .value("phone", "+1234567890")
            .value("hire_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("job_title", "Driver")
            .value("department", "department()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("PrivateCustomer")
            .value("id", 1_u64)
            .value("name", "Private Customer")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("address", "123 Main St")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CorporateCustomer")
            .value("id", 1_u64)
            .value("name", "Corporate Customer")
            .value("company_name", "Acme Corp")
            .value("tax_id", "TAX123456")
            .value("contact_person", "Jane Smith")
            .value("email", "jane.smith@acme.com")
            .value("phone", "+1234567891")
            .value("address", "456 Business Ave")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MovingService")
            .value("id", 1_u64)
            .value("name", "Standard Moving")
            .value("service_code", "MOV-STD")
            .value("base_price", "150.00")
            .value("description", "Standard household moving service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CleaningService")
            .value("id", 1_u64)
            .value("name", "Deep Cleaning")
            .value("service_code", "CLN-DP")
            .value("base_price", "80.00")
            .value("description", "Comprehensive deep cleaning service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Campaign")
            .value("id", 1_u64)
            .value("name", "Summer Move Promotion")
            .value("start_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("end_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("budget", "10000.00")
            .value("target_audience", "Residential")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("DiscountCode")
            .value("id", 1_u64)
            .value("code", "SUMMER10")
            .value("discount_percent", "10.00")
            .value("usage_limit", 500_i64)
            .value("used_count", 0_i64)
            .value("valid_from", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("valid_to", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Lead")
            .value("id", 1_u64)
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("source", "Online Ad")
            .value("status", "New")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Invoice")
            .value("id", 1_u64)
            .value("invoice_number", "INV-2024-001")
            .value("total_amount", "300.00")
            .value("tax_amount", "50.00")
            .value("status", "Sent")
            .value("customer", "customer()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Expense")
            .value("id", 1_u64)
            .value("description", "Fuel for truck")
            .value("amount", "75.50")
            .value("expense_type", "Fuel")
            .value("date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("VatRecord")
            .value("id", 1_u64)
            .value("vat_amount", "40.00")
            .value("tax_period", "Q1 2024")
            .value("filing_status", "Filed")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("FinancialSummary")
            .value("id", 1_u64)
            .value("period", "Monthly")
            .value("revenue", "5000.00")
            .value("expenses", "3000.00")
            .value("net_profit", "2000.00")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Vehicle")
            .value("id", 1_u64)
            .value("license_plate", "ABC123")
            .value("vehicle_type", "Truck")
            .value("capacity_kg", "5000.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("status", "Active")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Equipment")
            .value("id", 1_u64)
            .value("name", "Dolly")
            .value("equipment_type", "Moving Equipment")
            .value("purchase_cost", "150.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("condition", "Good")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Consumable")
            .value("id", 1_u64)
            .value("name", "Moving Blanket")
            .value("item_type", "Packing Material")
            .value("unit_cost", "8.50")
            .value("quantity_in_stock", 200_i64)
            .value("reorder_level", 50_i64)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("User")
            .value("id", 1_u64)
            .value("username", "john_doe")
            .value("email", "john@example.com")
            .value("password_hash", "hashed_password_123")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Role")
            .value("id", 1_u64)
            .value("name", "admin")
            .value("description", "System administrator")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Permission")
            .value("id", 1_u64)
            .value("name", "manage_users")
            .value("description", "Can manage user accounts")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("ApiEndpoint")
            .value("id", 1_u64)
            .value("path", "/api/v1/users")
            .value("method", "GET")
            .value("description", "Get user list")
            .value("version", "v1")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now()))
        .initial_graph(teaql_runtime::GraphNode::new("Webhook")
            .value("id", 1_u64)
            .value("url", "//example.com/webhook")
            .value("event_type", "invoice_paid")
            .value("secret_key", "webhook_secret_123")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
}

pub fn module_with_behaviors_and_checkers() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity_with_behavior::<Address, _>(AddressBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Address, _>::new(AddressChecker::default()))
        .entity_with_behavior::<MovingEvent, _>(MovingEventBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MovingEvent, _>::new(MovingEventChecker::default()))
        .entity_with_behavior::<Route, _>(RouteBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Route, _>::new(RouteChecker::default()))
        .entity_with_behavior::<TimeSlot, _>(TimeSlotBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<TimeSlot, _>::new(TimeSlotChecker::default()))
        .entity_with_behavior::<FulfillmentEvent, _>(FulfillmentEventBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .entity_with_behavior::<Staff, _>(StaffBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Staff, _>::new(StaffChecker::default()))
        .entity_with_behavior::<JobAssignment, _>(JobAssignmentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .entity_with_behavior::<WorkedHours, _>(WorkedHoursBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .entity_with_behavior::<Payroll, _>(PayrollBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Payroll, _>::new(PayrollChecker::default()))
        .entity_with_behavior::<Bonus, _>(BonusBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Bonus, _>::new(BonusChecker::default()))
        .entity_with_behavior::<LeaveTracking, _>(LeaveTrackingBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<LeaveTracking, _>::new(LeaveTrackingChecker::default()))
        .entity_with_behavior::<PrivateCustomer, _>(PrivateCustomerBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<PrivateCustomer, _>::new(PrivateCustomerChecker::default()))
        .entity_with_behavior::<CorporateCustomer, _>(CorporateCustomerBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CorporateCustomer, _>::new(CorporateCustomerChecker::default()))
        .entity_with_behavior::<CustomerContact, _>(CustomerContactBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CustomerContact, _>::new(CustomerContactChecker::default()))
        .entity_with_behavior::<MovingService, _>(MovingServiceBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MovingService, _>::new(MovingServiceChecker::default()))
        .entity_with_behavior::<CleaningService, _>(CleaningServiceBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CleaningService, _>::new(CleaningServiceChecker::default()))
        .entity_with_behavior::<Campaign, _>(CampaignBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Campaign, _>::new(CampaignChecker::default()))
        .entity_with_behavior::<DiscountCode, _>(DiscountCodeBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<DiscountCode, _>::new(DiscountCodeChecker::default()))
        .entity_with_behavior::<Lead, _>(LeadBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Lead, _>::new(LeadChecker::default()))
        .entity_with_behavior::<ConversionMetric, _>(ConversionMetricBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ConversionMetric, _>::new(ConversionMetricChecker::default()))
        .entity_with_behavior::<Payment, _>(PaymentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Payment, _>::new(PaymentChecker::default()))
        .entity_with_behavior::<Invoice, _>(InvoiceBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Invoice, _>::new(InvoiceChecker::default()))
        .entity_with_behavior::<Expense, _>(ExpenseBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Expense, _>::new(ExpenseChecker::default()))
        .entity_with_behavior::<VatRecord, _>(VatRecordBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<VatRecord, _>::new(VatRecordChecker::default()))
        .entity_with_behavior::<FinancialSummary, _>(FinancialSummaryBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<FinancialSummary, _>::new(FinancialSummaryChecker::default()))
        .entity_with_behavior::<Vehicle, _>(VehicleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Vehicle, _>::new(VehicleChecker::default()))
        .entity_with_behavior::<Equipment, _>(EquipmentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Equipment, _>::new(EquipmentChecker::default()))
        .entity_with_behavior::<Consumable, _>(ConsumableBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Consumable, _>::new(ConsumableChecker::default()))
        .entity_with_behavior::<User, _>(UserBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<User, _>::new(UserChecker::default()))
        .entity_with_behavior::<Role, _>(RoleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Role, _>::new(RoleChecker::default()))
        .entity_with_behavior::<Permission, _>(PermissionBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Permission, _>::new(PermissionChecker::default()))
        .entity_with_behavior::<UserRole, _>(UserRoleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .entity_with_behavior::<RolePermission, _>(RolePermissionBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<RolePermission, _>::new(RolePermissionChecker::default()))
        .entity_with_behavior::<AuthenticationLog, _>(AuthenticationLogBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<AuthenticationLog, _>::new(AuthenticationLogChecker::default()))
        .entity_with_behavior::<ActivityLog, _>(ActivityLogBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ActivityLog, _>::new(ActivityLogChecker::default()))
        .entity_with_behavior::<Notification, _>(NotificationBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Notification, _>::new(NotificationChecker::default()))
        .entity_with_behavior::<ApiEndpoint, _>(ApiEndpointBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ApiEndpoint, _>::new(ApiEndpointChecker::default()))
        .entity_with_behavior::<Webhook, _>(WebhookBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<Webhook, _>::new(WebhookChecker::default()))
        .initial_graph(teaql_runtime::GraphNode::new("Address")
            .value("id", 1_u64)
            .value("street", "123 Main St")
            .value("city", "New York")
            .value("state", "NY")
            .value("postal_code", 10001_i64)
            .value("country", "USA")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Staff")
            .value("id", 1_u64)
            .value("employee_id", "STF001")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@fastmovers.com")
            .value("phone", "+1234567890")
            .value("hire_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("job_title", "Driver")
            .value("department", "department()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("PrivateCustomer")
            .value("id", 1_u64)
            .value("name", "Private Customer")
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("address", "123 Main St")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CorporateCustomer")
            .value("id", 1_u64)
            .value("name", "Corporate Customer")
            .value("company_name", "Acme Corp")
            .value("tax_id", "TAX123456")
            .value("contact_person", "Jane Smith")
            .value("email", "jane.smith@acme.com")
            .value("phone", "+1234567891")
            .value("address", "456 Business Ave")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MovingService")
            .value("id", 1_u64)
            .value("name", "Standard Moving")
            .value("service_code", "MOV-STD")
            .value("base_price", "150.00")
            .value("description", "Standard household moving service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("CleaningService")
            .value("id", 1_u64)
            .value("name", "Deep Cleaning")
            .value("service_code", "CLN-DP")
            .value("base_price", "80.00")
            .value("description", "Comprehensive deep cleaning service")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Campaign")
            .value("id", 1_u64)
            .value("name", "Summer Move Promotion")
            .value("start_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("end_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("budget", "10000.00")
            .value("target_audience", "Residential")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("DiscountCode")
            .value("id", 1_u64)
            .value("code", "SUMMER10")
            .value("discount_percent", "10.00")
            .value("usage_limit", 500_i64)
            .value("used_count", 0_i64)
            .value("valid_from", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("valid_to", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Lead")
            .value("id", 1_u64)
            .value("first_name", "John")
            .value("last_name", "Doe")
            .value("email", "john.doe@example.com")
            .value("phone", "+1234567890")
            .value("source", "Online Ad")
            .value("status", "New")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Invoice")
            .value("id", 1_u64)
            .value("invoice_number", "INV-2024-001")
            .value("total_amount", "300.00")
            .value("tax_amount", "50.00")
            .value("status", "Sent")
            .value("customer", "customer()")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Expense")
            .value("id", 1_u64)
            .value("description", "Fuel for truck")
            .value("amount", "75.50")
            .value("expense_type", "Fuel")
            .value("date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("VatRecord")
            .value("id", 1_u64)
            .value("vat_amount", "40.00")
            .value("tax_period", "Q1 2024")
            .value("filing_status", "Filed")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("FinancialSummary")
            .value("id", 1_u64)
            .value("period", "Monthly")
            .value("revenue", "5000.00")
            .value("expenses", "3000.00")
            .value("net_profit", "2000.00")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Vehicle")
            .value("id", 1_u64)
            .value("license_plate", "ABC123")
            .value("vehicle_type", "Truck")
            .value("capacity_kg", "5000.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("status", "Active")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Equipment")
            .value("id", 1_u64)
            .value("name", "Dolly")
            .value("equipment_type", "Moving Equipment")
            .value("purchase_cost", "150.00")
            .value("purchase_date", chrono::NaiveDate::from_ymd_opt(1970, 1, 1).unwrap())
            .value("condition", "Good")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Consumable")
            .value("id", 1_u64)
            .value("name", "Moving Blanket")
            .value("item_type", "Packing Material")
            .value("unit_cost", "8.50")
            .value("quantity_in_stock", 200_i64)
            .value("reorder_level", 50_i64)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("User")
            .value("id", 1_u64)
            .value("username", "john_doe")
            .value("email", "john@example.com")
            .value("password_hash", "hashed_password_123")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Role")
            .value("id", 1_u64)
            .value("name", "admin")
            .value("description", "System administrator")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("Permission")
            .value("id", 1_u64)
            .value("name", "manage_users")
            .value("description", "Can manage user accounts")
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("ApiEndpoint")
            .value("id", 1_u64)
            .value("path", "/api/v1/users")
            .value("method", "GET")
            .value("description", "Get user list")
            .value("version", "v1")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now()))
        .initial_graph(teaql_runtime::GraphNode::new("Webhook")
            .value("id", 1_u64)
            .value("url", "//example.com/webhook")
            .value("event_type", "invoice_paid")
            .value("secret_key", "webhook_secret_123")
            .value("active", true)
            .value("create_time", chrono::Utc::now())
            .value("update_time", chrono::Utc::now())
            .value("version", 1_i64))
}