
use crate::*;
use teaql_core::TeaqlEntity;

use teaql_provider_sqlite::SqliteProviderExt as _;

pub type DataServiceDialect = teaql_provider_sqlite::SqliteDialect;
pub type DataServiceMutationExecutor = teaql_provider_sqlite::SqliteMutationExecutor;
pub type DataServiceMutationError = teaql_provider_sqlite::MutationExecutorError;
pub type DataServiceIdGenerator = teaql_provider_sqlite::SqliteIdSpaceGenerator;
pub type DataServicePool = std::sync::Arc<std::sync::Mutex<rusqlite::Connection>>;
pub type DataServiceExecutor = ServiceRuntimeExecutor;
pub type ServiceRuntime = teaql_runtime::UserContext;

pub const DATABASE_URL_ENV: &str = "MOVING_COMPANY_SERVICE_CORE_DATABASE_URL";
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServiceRuntimeConfig {
    pub database_url: String,
}

impl ServiceRuntimeConfig {
    pub fn from_env() -> Result<Self, ServiceRuntimeError> {
        Ok(Self {
            database_url: env_value(DATABASE_URL_ENV)?,
        })
    }
}

#[derive(Debug)]
pub enum ServiceRuntimeError {
    MissingEnv {
        name: &'static str,
        source: std::env::VarError,
    },
    ConnectionError(String),
    Rusqlite(rusqlite::Error),
    Runtime(teaql_runtime::RuntimeError),
}

impl std::fmt::Display for ServiceRuntimeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ServiceRuntimeError::MissingEnv { name, source } => {
                write!(f, "missing environment variable {name}: {source}")
            }
            ServiceRuntimeError::ConnectionError(err) => write!(f, "connection error: {err}"),
            ServiceRuntimeError::Rusqlite(err) => write!(f, "rusqlite error: {err}"),
            ServiceRuntimeError::Runtime(err) => write!(f, "runtime error: {err}"),
        }
    }
}

impl std::error::Error for ServiceRuntimeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ServiceRuntimeError::MissingEnv { source, .. } => Some(source),
            ServiceRuntimeError::ConnectionError(_) => None,
            ServiceRuntimeError::Rusqlite(err) => Some(err),
            ServiceRuntimeError::Runtime(err) => Some(err),
        }
    }
}

impl From<rusqlite::Error> for ServiceRuntimeError {
    fn from(err: rusqlite::Error) -> Self {
        ServiceRuntimeError::Rusqlite(err)
    }
}
impl From<teaql_runtime::RuntimeError> for ServiceRuntimeError {
    fn from(err: teaql_runtime::RuntimeError) -> Self {
        ServiceRuntimeError::Runtime(err)
    }
}

#[derive(Clone)]
pub struct LocalSchemaProvider;

impl teaql_data_service::SchemaProvider for LocalSchemaProvider {
    fn get_entity(&self, name: &str) -> Option<std::sync::Arc<teaql_core::EntityDescriptor>> {
        match name {
            "MoveStatus" => Some(std::sync::Arc::new(crate::MoveStatus::entity_descriptor())),
            "CompanyProfile" => Some(std::sync::Arc::new(crate::CompanyProfile::entity_descriptor())),
            "LocationAddress" => Some(std::sync::Arc::new(crate::LocationAddress::entity_descriptor())),
            "MoveOrder" => Some(std::sync::Arc::new(crate::MoveOrder::entity_descriptor())),
            "RoutePlan" => Some(std::sync::Arc::new(crate::RoutePlan::entity_descriptor())),
            "FulfillmentEvent" => Some(std::sync::Arc::new(crate::FulfillmentEvent::entity_descriptor())),
            "JobTitle" => Some(std::sync::Arc::new(crate::JobTitle::entity_descriptor())),
            "EmployeeRegistry" => Some(std::sync::Arc::new(crate::EmployeeRegistry::entity_descriptor())),
            "JobAssignment" => Some(std::sync::Arc::new(crate::JobAssignment::entity_descriptor())),
            "WorkedHours" => Some(std::sync::Arc::new(crate::WorkedHours::entity_descriptor())),
            "PayrollCalculation" => Some(std::sync::Arc::new(crate::PayrollCalculation::entity_descriptor())),
            "ShiftSchedule" => Some(std::sync::Arc::new(crate::ShiftSchedule::entity_descriptor())),
            "CustomerType" => Some(std::sync::Arc::new(crate::CustomerType::entity_descriptor())),
            "CustomerProfile" => Some(std::sync::Arc::new(crate::CustomerProfile::entity_descriptor())),
            "ContactPerson" => Some(std::sync::Arc::new(crate::ContactPerson::entity_descriptor())),
            "CustomerFeedback" => Some(std::sync::Arc::new(crate::CustomerFeedback::entity_descriptor())),
            "LoyaltyProgram" => Some(std::sync::Arc::new(crate::LoyaltyProgram::entity_descriptor())),
            "ServiceCategory" => Some(std::sync::Arc::new(crate::ServiceCategory::entity_descriptor())),
            "ServiceCatalog" => Some(std::sync::Arc::new(crate::ServiceCatalog::entity_descriptor())),
            "BoxRental" => Some(std::sync::Arc::new(crate::BoxRental::entity_descriptor())),
            "ServiceBundle" => Some(std::sync::Arc::new(crate::ServiceBundle::entity_descriptor())),
            "CampaignStatus" => Some(std::sync::Arc::new(crate::CampaignStatus::entity_descriptor())),
            "MarketingCampaign" => Some(std::sync::Arc::new(crate::MarketingCampaign::entity_descriptor())),
            "SalesLead" => Some(std::sync::Arc::new(crate::SalesLead::entity_descriptor())),
            "PaymentMethod" => Some(std::sync::Arc::new(crate::PaymentMethod::entity_descriptor())),
            "InvoiceDocument" => Some(std::sync::Arc::new(crate::InvoiceDocument::entity_descriptor())),
            "PaymentRecord" => Some(std::sync::Arc::new(crate::PaymentRecord::entity_descriptor())),
            "ExpenseRecord" => Some(std::sync::Arc::new(crate::ExpenseRecord::entity_descriptor())),
            "VehicleType" => Some(std::sync::Arc::new(crate::VehicleType::entity_descriptor())),
            "FleetVehicle" => Some(std::sync::Arc::new(crate::FleetVehicle::entity_descriptor())),
            "EquipmentItem" => Some(std::sync::Arc::new(crate::EquipmentItem::entity_descriptor())),
            "MaintenanceSchedule" => Some(std::sync::Arc::new(crate::MaintenanceSchedule::entity_descriptor())),
            "FuelLog" => Some(std::sync::Arc::new(crate::FuelLog::entity_descriptor())),
            "UserRole" => Some(std::sync::Arc::new(crate::UserRole::entity_descriptor())),
            "NotificationType" => Some(std::sync::Arc::new(crate::NotificationType::entity_descriptor())),
            "UserAccount" => Some(std::sync::Arc::new(crate::UserAccount::entity_descriptor())),
            "RoleDefinition" => Some(std::sync::Arc::new(crate::RoleDefinition::entity_descriptor())),
            "RoleAssignment" => Some(std::sync::Arc::new(crate::RoleAssignment::entity_descriptor())),
            "AuditLog" => Some(std::sync::Arc::new(crate::AuditLog::entity_descriptor())),
            "ServiceContract" => Some(std::sync::Arc::new(crate::ServiceContract::entity_descriptor())),
            _ => None,
        }
    }
}

#[derive(Clone)]
pub struct ServiceRuntimeExecutor {
    inner: teaql_sql::SqlDataServiceExecutor<
        DataServiceDialect,
        DataServiceMutationExecutor,
        LocalSchemaProvider
    >,
}

impl ServiceRuntimeExecutor {
    pub fn new(inner: DataServiceMutationExecutor) -> Self {
        Self {
            inner: teaql_sql::SqlDataServiceExecutor::new(
                DataServiceDialect::default(),
                inner,
                LocalSchemaProvider
            ),
        }
    }

}

impl teaql_data_service::DataServiceExecutor for ServiceRuntimeExecutor {
    type Error = teaql_sql::SqlExecutorError<DataServiceMutationError>;
    fn capabilities(&self) -> teaql_data_service::DataServiceCapabilities {
        teaql_data_service::DataServiceExecutor::capabilities(&self.inner)
    }
}

impl teaql_data_service::QueryExecutor for ServiceRuntimeExecutor {
    async fn query(&self, request: teaql_data_service::QueryRequest) -> Result<teaql_data_service::QueryResult, Self::Error> {
        teaql_data_service::QueryExecutor::query(&self.inner, request).await
    }
}

impl teaql_data_service::StreamQueryExecutor for ServiceRuntimeExecutor {
    async fn query_stream(&self, request: teaql_data_service::QueryRequest, chunk_size: usize) -> Result<Vec<teaql_data_service::StreamChunk>, Self::Error> {
        teaql_data_service::StreamQueryExecutor::query_stream(&self.inner, request, chunk_size).await
    }
}

impl teaql_data_service::MutationExecutor for ServiceRuntimeExecutor {
    async fn mutate(&self, request: teaql_data_service::MutationRequest) -> Result<teaql_data_service::MutationResult, Self::Error> {
        teaql_data_service::MutationExecutor::mutate(&self.inner, request).await
    }
}

impl teaql_data_service::TransactionExecutor for ServiceRuntimeExecutor {
    type Tx<'a> = teaql_sql::SqlDataServiceTransaction<'a, DataServiceDialect, <DataServiceMutationExecutor as teaql_sql::SqlTransactionTransport>::Tx<'a>, LocalSchemaProvider> where Self: 'a;

    async fn begin(&self) -> Result<Self::Tx<'_ >, Self::Error> {
        teaql_data_service::TransactionExecutor::begin(&self.inner).await
    }
}

pub async fn service_runtime_from_env() -> Result<ServiceRuntime, ServiceRuntimeError> {
    service_runtime(ServiceRuntimeConfig::from_env()?).await
}

pub async fn service_runtime(config: ServiceRuntimeConfig) -> Result<ServiceRuntime, ServiceRuntimeError> {
    let pool = connect_data_service_pool(&config).await?;
    service_runtime_from_pool(pool).await
}

pub async fn service_runtime_from_pool(pool: DataServicePool) -> Result<ServiceRuntime, ServiceRuntimeError> {
    let mutation_executor = DataServiceMutationExecutor::new(pool);
    let id_generator = DataServiceIdGenerator::from_executor(mutation_executor.clone());let mut context = module_with_behaviors_and_checkers().into_context();
    context.set_internal_id_generator(id_generator);
    context.use_sqlite_provider(mutation_executor.clone());
    let executor = ServiceRuntimeExecutor::new(mutation_executor);
    context.register_executor(executor.clone());
    context.insert_resource(executor);

    // 自动加载 Zero-Code 审计配置与 Schema 模式
    let env_config = teaql_tool_core::audit_config_from_env(&[
        "move_status_data", "company_profile_data", "location_address_data", "move_order_data", "route_plan_data", "fulfillment_event_data", "job_title_data", "employee_registry_data", "job_assignment_data", "worked_hours_data", "payroll_calculation_data", "shift_schedule_data", "customer_type_data", "customer_profile_data", "contact_person_data", "customer_feedback_data", "loyalty_program_data", "service_category_data", "service_catalog_data", "box_rental_data", "service_bundle_data", "campaign_status_data", "marketing_campaign_data", "sales_lead_data", "payment_method_data", "invoice_document_data", "payment_record_data", "expense_record_data", "vehicle_type_data", "fleet_vehicle_data", "equipment_item_data", "maintenance_schedule_data", "fuel_log_data", "user_role_data", "notification_type_data", "user_account_data", "role_definition_data", "role_assignment_data", "audit_log_data", "service_contract_data"
    ]);
    let schema_mode = env_config.schema_mode;
    context.insert_resource(env_config.config.clone());
    context.insert_resource(env_config);

    match schema_mode {
        teaql_tool_core::SchemaMode::Execute => {
            context.ensure_schema().await?;
        }
        teaql_tool_core::SchemaMode::DryRun => {
            // DryRun: 目前等效于验证
            context.ensure_schema().await?;
        }
        teaql_tool_core::SchemaMode::Verify => {
            context.ensure_schema().await?;
        }
    }

    Ok(context)
}



fn env_value(name: &'static str) -> Result<String, ServiceRuntimeError> {
    std::env::var(name).map_err(|source| ServiceRuntimeError::MissingEnv { name, source })
}

async fn connect_data_service_pool(config: &ServiceRuntimeConfig) -> Result<DataServicePool, ServiceRuntimeError> {
    let url = &config.database_url;
    let sanitized_url = if url.starts_with("sqlite:") { url.strip_prefix("sqlite:").unwrap().trim_start_matches("//") } else { url };
    let pure_file_path = sanitized_url.split('?').next().unwrap_or(sanitized_url);
    let path = std::path::Path::new(pure_file_path);
    if let Some(parent) = path.parent() { if !parent.as_os_str().is_empty() { std::fs::create_dir_all(parent).map_err(|e| ServiceRuntimeError::ConnectionError(e.to_string()))?; } }
    Ok(std::sync::Arc::new(std::sync::Mutex::new(rusqlite::Connection::open(pure_file_path).map_err(|e| ServiceRuntimeError::ConnectionError(e.to_string()))?)))
}

pub fn repository_registry() -> teaql_runtime::InMemoryEntityRegistry {
    teaql_runtime::InMemoryEntityRegistry::new()
        .with_entity("MoveStatus")
        .with_entity("CompanyProfile")
        .with_entity("LocationAddress")
        .with_entity("MoveOrder")
        .with_entity("RoutePlan")
        .with_entity("FulfillmentEvent")
        .with_entity("JobTitle")
        .with_entity("EmployeeRegistry")
        .with_entity("JobAssignment")
        .with_entity("WorkedHours")
        .with_entity("PayrollCalculation")
        .with_entity("ShiftSchedule")
        .with_entity("CustomerType")
        .with_entity("CustomerProfile")
        .with_entity("ContactPerson")
        .with_entity("CustomerFeedback")
        .with_entity("LoyaltyProgram")
        .with_entity("ServiceCategory")
        .with_entity("ServiceCatalog")
        .with_entity("BoxRental")
        .with_entity("ServiceBundle")
        .with_entity("CampaignStatus")
        .with_entity("MarketingCampaign")
        .with_entity("SalesLead")
        .with_entity("PaymentMethod")
        .with_entity("InvoiceDocument")
        .with_entity("PaymentRecord")
        .with_entity("ExpenseRecord")
        .with_entity("VehicleType")
        .with_entity("FleetVehicle")
        .with_entity("EquipmentItem")
        .with_entity("MaintenanceSchedule")
        .with_entity("FuelLog")
        .with_entity("UserRole")
        .with_entity("NotificationType")
        .with_entity("UserAccount")
        .with_entity("RoleDefinition")
        .with_entity("RoleAssignment")
        .with_entity("AuditLog")
        .with_entity("ServiceContract")
}

pub fn behavior_registry() -> teaql_runtime::InMemoryEntityDataServiceBehaviorRegistry {
    teaql_runtime::InMemoryEntityDataServiceBehaviorRegistry::new()
        .with_behavior("MoveStatus", MoveStatusBehavior::default())
        .with_behavior("CompanyProfile", CompanyProfileBehavior::default())
        .with_behavior("LocationAddress", LocationAddressBehavior::default())
        .with_behavior("MoveOrder", MoveOrderBehavior::default())
        .with_behavior("RoutePlan", RoutePlanBehavior::default())
        .with_behavior("FulfillmentEvent", FulfillmentEventBehavior::default())
        .with_behavior("JobTitle", JobTitleBehavior::default())
        .with_behavior("EmployeeRegistry", EmployeeRegistryBehavior::default())
        .with_behavior("JobAssignment", JobAssignmentBehavior::default())
        .with_behavior("WorkedHours", WorkedHoursBehavior::default())
        .with_behavior("PayrollCalculation", PayrollCalculationBehavior::default())
        .with_behavior("ShiftSchedule", ShiftScheduleBehavior::default())
        .with_behavior("CustomerType", CustomerTypeBehavior::default())
        .with_behavior("CustomerProfile", CustomerProfileBehavior::default())
        .with_behavior("ContactPerson", ContactPersonBehavior::default())
        .with_behavior("CustomerFeedback", CustomerFeedbackBehavior::default())
        .with_behavior("LoyaltyProgram", LoyaltyProgramBehavior::default())
        .with_behavior("ServiceCategory", ServiceCategoryBehavior::default())
        .with_behavior("ServiceCatalog", ServiceCatalogBehavior::default())
        .with_behavior("BoxRental", BoxRentalBehavior::default())
        .with_behavior("ServiceBundle", ServiceBundleBehavior::default())
        .with_behavior("CampaignStatus", CampaignStatusBehavior::default())
        .with_behavior("MarketingCampaign", MarketingCampaignBehavior::default())
        .with_behavior("SalesLead", SalesLeadBehavior::default())
        .with_behavior("PaymentMethod", PaymentMethodBehavior::default())
        .with_behavior("InvoiceDocument", InvoiceDocumentBehavior::default())
        .with_behavior("PaymentRecord", PaymentRecordBehavior::default())
        .with_behavior("ExpenseRecord", ExpenseRecordBehavior::default())
        .with_behavior("VehicleType", VehicleTypeBehavior::default())
        .with_behavior("FleetVehicle", FleetVehicleBehavior::default())
        .with_behavior("EquipmentItem", EquipmentItemBehavior::default())
        .with_behavior("MaintenanceSchedule", MaintenanceScheduleBehavior::default())
        .with_behavior("FuelLog", FuelLogBehavior::default())
        .with_behavior("UserRole", UserRoleBehavior::default())
        .with_behavior("NotificationType", NotificationTypeBehavior::default())
        .with_behavior("UserAccount", UserAccountBehavior::default())
        .with_behavior("RoleDefinition", RoleDefinitionBehavior::default())
        .with_behavior("RoleAssignment", RoleAssignmentBehavior::default())
        .with_behavior("AuditLog", AuditLogBehavior::default())
        .with_behavior("ServiceContract", ServiceContractBehavior::default())
}

pub fn checker_registry() -> teaql_runtime::InMemoryCheckerRegistry {
    teaql_runtime::InMemoryCheckerRegistry::new()
        .with_checker(teaql_runtime::TypedEntityChecker::<MoveStatus, _>::new(MoveStatusChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CompanyProfile, _>::new(CompanyProfileChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<LocationAddress, _>::new(LocationAddressChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<MoveOrder, _>::new(MoveOrderChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<RoutePlan, _>::new(RoutePlanChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<JobTitle, _>::new(JobTitleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<EmployeeRegistry, _>::new(EmployeeRegistryChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<PayrollCalculation, _>::new(PayrollCalculationChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ShiftSchedule, _>::new(ShiftScheduleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CustomerType, _>::new(CustomerTypeChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CustomerProfile, _>::new(CustomerProfileChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ContactPerson, _>::new(ContactPersonChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CustomerFeedback, _>::new(CustomerFeedbackChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<LoyaltyProgram, _>::new(LoyaltyProgramChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ServiceCategory, _>::new(ServiceCategoryChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ServiceCatalog, _>::new(ServiceCatalogChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<BoxRental, _>::new(BoxRentalChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ServiceBundle, _>::new(ServiceBundleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<CampaignStatus, _>::new(CampaignStatusChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<MarketingCampaign, _>::new(MarketingCampaignChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<SalesLead, _>::new(SalesLeadChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<PaymentMethod, _>::new(PaymentMethodChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<InvoiceDocument, _>::new(InvoiceDocumentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<PaymentRecord, _>::new(PaymentRecordChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ExpenseRecord, _>::new(ExpenseRecordChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<VehicleType, _>::new(VehicleTypeChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<FleetVehicle, _>::new(FleetVehicleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<EquipmentItem, _>::new(EquipmentItemChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<MaintenanceSchedule, _>::new(MaintenanceScheduleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<FuelLog, _>::new(FuelLogChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<NotificationType, _>::new(NotificationTypeChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<UserAccount, _>::new(UserAccountChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<RoleDefinition, _>::new(RoleDefinitionChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<RoleAssignment, _>::new(RoleAssignmentChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<AuditLog, _>::new(AuditLogChecker::default()))
        .with_checker(teaql_runtime::TypedEntityChecker::<ServiceContract, _>::new(ServiceContractChecker::default()))
}

pub fn module() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity::<MoveStatus>()
        .entity::<CompanyProfile>()
        .entity::<LocationAddress>()
        .entity::<MoveOrder>()
        .entity::<RoutePlan>()
        .entity::<FulfillmentEvent>()
        .entity::<JobTitle>()
        .entity::<EmployeeRegistry>()
        .entity::<JobAssignment>()
        .entity::<WorkedHours>()
        .entity::<PayrollCalculation>()
        .entity::<ShiftSchedule>()
        .entity::<CustomerType>()
        .entity::<CustomerProfile>()
        .entity::<ContactPerson>()
        .entity::<CustomerFeedback>()
        .entity::<LoyaltyProgram>()
        .entity::<ServiceCategory>()
        .entity::<ServiceCatalog>()
        .entity::<BoxRental>()
        .entity::<ServiceBundle>()
        .entity::<CampaignStatus>()
        .entity::<MarketingCampaign>()
        .entity::<SalesLead>()
        .entity::<PaymentMethod>()
        .entity::<InvoiceDocument>()
        .entity::<PaymentRecord>()
        .entity::<ExpenseRecord>()
        .entity::<VehicleType>()
        .entity::<FleetVehicle>()
        .entity::<EquipmentItem>()
        .entity::<MaintenanceSchedule>()
        .entity::<FuelLog>()
        .entity::<UserRole>()
        .entity::<NotificationType>()
        .entity::<UserAccount>()
        .entity::<RoleDefinition>()
        .entity::<RoleAssignment>()
        .entity::<AuditLog>()
        .entity::<ServiceContract>()
        .initial_graph(teaql_runtime::GraphNode::new("CompanyProfile")
            .value("id", 1_u64)
            .value("company_name", "SwiftMove Logistics")
            .value("registration_number", "REG-2020-001")
            .value("create_time", teaql_core::time::Timestamp::now())
            .value("update_time", teaql_core::time::Timestamp::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1001_u64)
            .value("name", "Scheduled")
            .value("code", "SCHEDULED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1002_u64)
            .value("name", "In Transit")
            .value("code", "IN_TRANSIT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1003_u64)
            .value("name", "Delivered")
            .value("code", "DELIVERED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1004_u64)
            .value("name", "Cancelled")
            .value("code", "CANCELLED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4001_u64)
            .value("name", "Driver")
            .value("code", "DRIVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4002_u64)
            .value("name", "Mover")
            .value("code", "MOVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4003_u64)
            .value("name", "Dispatcher")
            .value("code", "DISPATCHER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4004_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6001_u64)
            .value("name", "Private")
            .value("code", "PRIVATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6002_u64)
            .value("name", "Corporate")
            .value("code", "CORPORATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8001_u64)
            .value("name", "Moving")
            .value("code", "MOVING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8002_u64)
            .value("name", "Cleaning")
            .value("code", "CLEANING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8003_u64)
            .value("name", "Packing")
            .value("code", "PACKING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8004_u64)
            .value("name", "Storage")
            .value("code", "STORAGE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9001_u64)
            .value("name", "Planned")
            .value("code", "PLANNED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9002_u64)
            .value("name", "Active")
            .value("code", "ACTIVE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9003_u64)
            .value("name", "Completed")
            .value("code", "COMPLETED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10001_u64)
            .value("name", "Credit Card")
            .value("code", "CREDIT_CARD")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10002_u64)
            .value("name", "Bank Transfer")
            .value("code", "BANK_TRANSFER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10003_u64)
            .value("name", "Cash")
            .value("code", "CASH")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12001_u64)
            .value("name", "Small Van")
            .value("code", "SMALL_VAN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12002_u64)
            .value("name", "Medium Truck")
            .value("code", "MEDIUM_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12003_u64)
            .value("name", "Large Truck")
            .value("code", "LARGE_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14001_u64)
            .value("name", "Administrator")
            .value("code", "ADMIN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14002_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14003_u64)
            .value("name", "Employee")
            .value("code", "EMPLOYEE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14004_u64)
            .value("name", "Customer")
            .value("code", "CUSTOMER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15001_u64)
            .value("name", "Operational")
            .value("code", "OPERATIONAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15002_u64)
            .value("name", "Financial")
            .value("code", "FINANCIAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15003_u64)
            .value("name", "Alert")
            .value("code", "ALERT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
}

pub fn module_with_checkers() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity::<MoveStatus>()
        .checker(teaql_runtime::TypedEntityChecker::<MoveStatus, _>::new(MoveStatusChecker::default()))
        .entity::<CompanyProfile>()
        .checker(teaql_runtime::TypedEntityChecker::<CompanyProfile, _>::new(CompanyProfileChecker::default()))
        .entity::<LocationAddress>()
        .checker(teaql_runtime::TypedEntityChecker::<LocationAddress, _>::new(LocationAddressChecker::default()))
        .entity::<MoveOrder>()
        .checker(teaql_runtime::TypedEntityChecker::<MoveOrder, _>::new(MoveOrderChecker::default()))
        .entity::<RoutePlan>()
        .checker(teaql_runtime::TypedEntityChecker::<RoutePlan, _>::new(RoutePlanChecker::default()))
        .entity::<FulfillmentEvent>()
        .checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .entity::<JobTitle>()
        .checker(teaql_runtime::TypedEntityChecker::<JobTitle, _>::new(JobTitleChecker::default()))
        .entity::<EmployeeRegistry>()
        .checker(teaql_runtime::TypedEntityChecker::<EmployeeRegistry, _>::new(EmployeeRegistryChecker::default()))
        .entity::<JobAssignment>()
        .checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .entity::<WorkedHours>()
        .checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .entity::<PayrollCalculation>()
        .checker(teaql_runtime::TypedEntityChecker::<PayrollCalculation, _>::new(PayrollCalculationChecker::default()))
        .entity::<ShiftSchedule>()
        .checker(teaql_runtime::TypedEntityChecker::<ShiftSchedule, _>::new(ShiftScheduleChecker::default()))
        .entity::<CustomerType>()
        .checker(teaql_runtime::TypedEntityChecker::<CustomerType, _>::new(CustomerTypeChecker::default()))
        .entity::<CustomerProfile>()
        .checker(teaql_runtime::TypedEntityChecker::<CustomerProfile, _>::new(CustomerProfileChecker::default()))
        .entity::<ContactPerson>()
        .checker(teaql_runtime::TypedEntityChecker::<ContactPerson, _>::new(ContactPersonChecker::default()))
        .entity::<CustomerFeedback>()
        .checker(teaql_runtime::TypedEntityChecker::<CustomerFeedback, _>::new(CustomerFeedbackChecker::default()))
        .entity::<LoyaltyProgram>()
        .checker(teaql_runtime::TypedEntityChecker::<LoyaltyProgram, _>::new(LoyaltyProgramChecker::default()))
        .entity::<ServiceCategory>()
        .checker(teaql_runtime::TypedEntityChecker::<ServiceCategory, _>::new(ServiceCategoryChecker::default()))
        .entity::<ServiceCatalog>()
        .checker(teaql_runtime::TypedEntityChecker::<ServiceCatalog, _>::new(ServiceCatalogChecker::default()))
        .entity::<BoxRental>()
        .checker(teaql_runtime::TypedEntityChecker::<BoxRental, _>::new(BoxRentalChecker::default()))
        .entity::<ServiceBundle>()
        .checker(teaql_runtime::TypedEntityChecker::<ServiceBundle, _>::new(ServiceBundleChecker::default()))
        .entity::<CampaignStatus>()
        .checker(teaql_runtime::TypedEntityChecker::<CampaignStatus, _>::new(CampaignStatusChecker::default()))
        .entity::<MarketingCampaign>()
        .checker(teaql_runtime::TypedEntityChecker::<MarketingCampaign, _>::new(MarketingCampaignChecker::default()))
        .entity::<SalesLead>()
        .checker(teaql_runtime::TypedEntityChecker::<SalesLead, _>::new(SalesLeadChecker::default()))
        .entity::<PaymentMethod>()
        .checker(teaql_runtime::TypedEntityChecker::<PaymentMethod, _>::new(PaymentMethodChecker::default()))
        .entity::<InvoiceDocument>()
        .checker(teaql_runtime::TypedEntityChecker::<InvoiceDocument, _>::new(InvoiceDocumentChecker::default()))
        .entity::<PaymentRecord>()
        .checker(teaql_runtime::TypedEntityChecker::<PaymentRecord, _>::new(PaymentRecordChecker::default()))
        .entity::<ExpenseRecord>()
        .checker(teaql_runtime::TypedEntityChecker::<ExpenseRecord, _>::new(ExpenseRecordChecker::default()))
        .entity::<VehicleType>()
        .checker(teaql_runtime::TypedEntityChecker::<VehicleType, _>::new(VehicleTypeChecker::default()))
        .entity::<FleetVehicle>()
        .checker(teaql_runtime::TypedEntityChecker::<FleetVehicle, _>::new(FleetVehicleChecker::default()))
        .entity::<EquipmentItem>()
        .checker(teaql_runtime::TypedEntityChecker::<EquipmentItem, _>::new(EquipmentItemChecker::default()))
        .entity::<MaintenanceSchedule>()
        .checker(teaql_runtime::TypedEntityChecker::<MaintenanceSchedule, _>::new(MaintenanceScheduleChecker::default()))
        .entity::<FuelLog>()
        .checker(teaql_runtime::TypedEntityChecker::<FuelLog, _>::new(FuelLogChecker::default()))
        .entity::<UserRole>()
        .checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .entity::<NotificationType>()
        .checker(teaql_runtime::TypedEntityChecker::<NotificationType, _>::new(NotificationTypeChecker::default()))
        .entity::<UserAccount>()
        .checker(teaql_runtime::TypedEntityChecker::<UserAccount, _>::new(UserAccountChecker::default()))
        .entity::<RoleDefinition>()
        .checker(teaql_runtime::TypedEntityChecker::<RoleDefinition, _>::new(RoleDefinitionChecker::default()))
        .entity::<RoleAssignment>()
        .checker(teaql_runtime::TypedEntityChecker::<RoleAssignment, _>::new(RoleAssignmentChecker::default()))
        .entity::<AuditLog>()
        .checker(teaql_runtime::TypedEntityChecker::<AuditLog, _>::new(AuditLogChecker::default()))
        .entity::<ServiceContract>()
        .checker(teaql_runtime::TypedEntityChecker::<ServiceContract, _>::new(ServiceContractChecker::default()))
        .initial_graph(teaql_runtime::GraphNode::new("CompanyProfile")
            .value("id", 1_u64)
            .value("company_name", "SwiftMove Logistics")
            .value("registration_number", "REG-2020-001")
            .value("create_time", teaql_core::time::Timestamp::now())
            .value("update_time", teaql_core::time::Timestamp::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1001_u64)
            .value("name", "Scheduled")
            .value("code", "SCHEDULED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1002_u64)
            .value("name", "In Transit")
            .value("code", "IN_TRANSIT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1003_u64)
            .value("name", "Delivered")
            .value("code", "DELIVERED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1004_u64)
            .value("name", "Cancelled")
            .value("code", "CANCELLED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4001_u64)
            .value("name", "Driver")
            .value("code", "DRIVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4002_u64)
            .value("name", "Mover")
            .value("code", "MOVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4003_u64)
            .value("name", "Dispatcher")
            .value("code", "DISPATCHER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4004_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6001_u64)
            .value("name", "Private")
            .value("code", "PRIVATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6002_u64)
            .value("name", "Corporate")
            .value("code", "CORPORATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8001_u64)
            .value("name", "Moving")
            .value("code", "MOVING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8002_u64)
            .value("name", "Cleaning")
            .value("code", "CLEANING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8003_u64)
            .value("name", "Packing")
            .value("code", "PACKING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8004_u64)
            .value("name", "Storage")
            .value("code", "STORAGE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9001_u64)
            .value("name", "Planned")
            .value("code", "PLANNED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9002_u64)
            .value("name", "Active")
            .value("code", "ACTIVE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9003_u64)
            .value("name", "Completed")
            .value("code", "COMPLETED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10001_u64)
            .value("name", "Credit Card")
            .value("code", "CREDIT_CARD")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10002_u64)
            .value("name", "Bank Transfer")
            .value("code", "BANK_TRANSFER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10003_u64)
            .value("name", "Cash")
            .value("code", "CASH")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12001_u64)
            .value("name", "Small Van")
            .value("code", "SMALL_VAN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12002_u64)
            .value("name", "Medium Truck")
            .value("code", "MEDIUM_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12003_u64)
            .value("name", "Large Truck")
            .value("code", "LARGE_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14001_u64)
            .value("name", "Administrator")
            .value("code", "ADMIN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14002_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14003_u64)
            .value("name", "Employee")
            .value("code", "EMPLOYEE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14004_u64)
            .value("name", "Customer")
            .value("code", "CUSTOMER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15001_u64)
            .value("name", "Operational")
            .value("code", "OPERATIONAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15002_u64)
            .value("name", "Financial")
            .value("code", "FINANCIAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15003_u64)
            .value("name", "Alert")
            .value("code", "ALERT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
}

pub fn module_with_behaviors() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity_with_behavior::<MoveStatus, _>(MoveStatusBehavior::default())
        .entity_with_behavior::<CompanyProfile, _>(CompanyProfileBehavior::default())
        .entity_with_behavior::<LocationAddress, _>(LocationAddressBehavior::default())
        .entity_with_behavior::<MoveOrder, _>(MoveOrderBehavior::default())
        .entity_with_behavior::<RoutePlan, _>(RoutePlanBehavior::default())
        .entity_with_behavior::<FulfillmentEvent, _>(FulfillmentEventBehavior::default())
        .entity_with_behavior::<JobTitle, _>(JobTitleBehavior::default())
        .entity_with_behavior::<EmployeeRegistry, _>(EmployeeRegistryBehavior::default())
        .entity_with_behavior::<JobAssignment, _>(JobAssignmentBehavior::default())
        .entity_with_behavior::<WorkedHours, _>(WorkedHoursBehavior::default())
        .entity_with_behavior::<PayrollCalculation, _>(PayrollCalculationBehavior::default())
        .entity_with_behavior::<ShiftSchedule, _>(ShiftScheduleBehavior::default())
        .entity_with_behavior::<CustomerType, _>(CustomerTypeBehavior::default())
        .entity_with_behavior::<CustomerProfile, _>(CustomerProfileBehavior::default())
        .entity_with_behavior::<ContactPerson, _>(ContactPersonBehavior::default())
        .entity_with_behavior::<CustomerFeedback, _>(CustomerFeedbackBehavior::default())
        .entity_with_behavior::<LoyaltyProgram, _>(LoyaltyProgramBehavior::default())
        .entity_with_behavior::<ServiceCategory, _>(ServiceCategoryBehavior::default())
        .entity_with_behavior::<ServiceCatalog, _>(ServiceCatalogBehavior::default())
        .entity_with_behavior::<BoxRental, _>(BoxRentalBehavior::default())
        .entity_with_behavior::<ServiceBundle, _>(ServiceBundleBehavior::default())
        .entity_with_behavior::<CampaignStatus, _>(CampaignStatusBehavior::default())
        .entity_with_behavior::<MarketingCampaign, _>(MarketingCampaignBehavior::default())
        .entity_with_behavior::<SalesLead, _>(SalesLeadBehavior::default())
        .entity_with_behavior::<PaymentMethod, _>(PaymentMethodBehavior::default())
        .entity_with_behavior::<InvoiceDocument, _>(InvoiceDocumentBehavior::default())
        .entity_with_behavior::<PaymentRecord, _>(PaymentRecordBehavior::default())
        .entity_with_behavior::<ExpenseRecord, _>(ExpenseRecordBehavior::default())
        .entity_with_behavior::<VehicleType, _>(VehicleTypeBehavior::default())
        .entity_with_behavior::<FleetVehicle, _>(FleetVehicleBehavior::default())
        .entity_with_behavior::<EquipmentItem, _>(EquipmentItemBehavior::default())
        .entity_with_behavior::<MaintenanceSchedule, _>(MaintenanceScheduleBehavior::default())
        .entity_with_behavior::<FuelLog, _>(FuelLogBehavior::default())
        .entity_with_behavior::<UserRole, _>(UserRoleBehavior::default())
        .entity_with_behavior::<NotificationType, _>(NotificationTypeBehavior::default())
        .entity_with_behavior::<UserAccount, _>(UserAccountBehavior::default())
        .entity_with_behavior::<RoleDefinition, _>(RoleDefinitionBehavior::default())
        .entity_with_behavior::<RoleAssignment, _>(RoleAssignmentBehavior::default())
        .entity_with_behavior::<AuditLog, _>(AuditLogBehavior::default())
        .entity_with_behavior::<ServiceContract, _>(ServiceContractBehavior::default())
        .initial_graph(teaql_runtime::GraphNode::new("CompanyProfile")
            .value("id", 1_u64)
            .value("company_name", "SwiftMove Logistics")
            .value("registration_number", "REG-2020-001")
            .value("create_time", teaql_core::time::Timestamp::now())
            .value("update_time", teaql_core::time::Timestamp::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1001_u64)
            .value("name", "Scheduled")
            .value("code", "SCHEDULED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1002_u64)
            .value("name", "In Transit")
            .value("code", "IN_TRANSIT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1003_u64)
            .value("name", "Delivered")
            .value("code", "DELIVERED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1004_u64)
            .value("name", "Cancelled")
            .value("code", "CANCELLED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4001_u64)
            .value("name", "Driver")
            .value("code", "DRIVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4002_u64)
            .value("name", "Mover")
            .value("code", "MOVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4003_u64)
            .value("name", "Dispatcher")
            .value("code", "DISPATCHER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4004_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6001_u64)
            .value("name", "Private")
            .value("code", "PRIVATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6002_u64)
            .value("name", "Corporate")
            .value("code", "CORPORATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8001_u64)
            .value("name", "Moving")
            .value("code", "MOVING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8002_u64)
            .value("name", "Cleaning")
            .value("code", "CLEANING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8003_u64)
            .value("name", "Packing")
            .value("code", "PACKING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8004_u64)
            .value("name", "Storage")
            .value("code", "STORAGE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9001_u64)
            .value("name", "Planned")
            .value("code", "PLANNED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9002_u64)
            .value("name", "Active")
            .value("code", "ACTIVE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9003_u64)
            .value("name", "Completed")
            .value("code", "COMPLETED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10001_u64)
            .value("name", "Credit Card")
            .value("code", "CREDIT_CARD")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10002_u64)
            .value("name", "Bank Transfer")
            .value("code", "BANK_TRANSFER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10003_u64)
            .value("name", "Cash")
            .value("code", "CASH")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12001_u64)
            .value("name", "Small Van")
            .value("code", "SMALL_VAN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12002_u64)
            .value("name", "Medium Truck")
            .value("code", "MEDIUM_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12003_u64)
            .value("name", "Large Truck")
            .value("code", "LARGE_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14001_u64)
            .value("name", "Administrator")
            .value("code", "ADMIN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14002_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14003_u64)
            .value("name", "Employee")
            .value("code", "EMPLOYEE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14004_u64)
            .value("name", "Customer")
            .value("code", "CUSTOMER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15001_u64)
            .value("name", "Operational")
            .value("code", "OPERATIONAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15002_u64)
            .value("name", "Financial")
            .value("code", "FINANCIAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15003_u64)
            .value("name", "Alert")
            .value("code", "ALERT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
}

pub fn module_with_behaviors_and_checkers() -> teaql_runtime::RuntimeModule {
    teaql_runtime::RuntimeModule::new()
        .entity_with_behavior::<MoveStatus, _>(MoveStatusBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MoveStatus, _>::new(MoveStatusChecker::default()))
        .entity_with_behavior::<CompanyProfile, _>(CompanyProfileBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CompanyProfile, _>::new(CompanyProfileChecker::default()))
        .entity_with_behavior::<LocationAddress, _>(LocationAddressBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<LocationAddress, _>::new(LocationAddressChecker::default()))
        .entity_with_behavior::<MoveOrder, _>(MoveOrderBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MoveOrder, _>::new(MoveOrderChecker::default()))
        .entity_with_behavior::<RoutePlan, _>(RoutePlanBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<RoutePlan, _>::new(RoutePlanChecker::default()))
        .entity_with_behavior::<FulfillmentEvent, _>(FulfillmentEventBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<FulfillmentEvent, _>::new(FulfillmentEventChecker::default()))
        .entity_with_behavior::<JobTitle, _>(JobTitleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<JobTitle, _>::new(JobTitleChecker::default()))
        .entity_with_behavior::<EmployeeRegistry, _>(EmployeeRegistryBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<EmployeeRegistry, _>::new(EmployeeRegistryChecker::default()))
        .entity_with_behavior::<JobAssignment, _>(JobAssignmentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<JobAssignment, _>::new(JobAssignmentChecker::default()))
        .entity_with_behavior::<WorkedHours, _>(WorkedHoursBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<WorkedHours, _>::new(WorkedHoursChecker::default()))
        .entity_with_behavior::<PayrollCalculation, _>(PayrollCalculationBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<PayrollCalculation, _>::new(PayrollCalculationChecker::default()))
        .entity_with_behavior::<ShiftSchedule, _>(ShiftScheduleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ShiftSchedule, _>::new(ShiftScheduleChecker::default()))
        .entity_with_behavior::<CustomerType, _>(CustomerTypeBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CustomerType, _>::new(CustomerTypeChecker::default()))
        .entity_with_behavior::<CustomerProfile, _>(CustomerProfileBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CustomerProfile, _>::new(CustomerProfileChecker::default()))
        .entity_with_behavior::<ContactPerson, _>(ContactPersonBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ContactPerson, _>::new(ContactPersonChecker::default()))
        .entity_with_behavior::<CustomerFeedback, _>(CustomerFeedbackBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CustomerFeedback, _>::new(CustomerFeedbackChecker::default()))
        .entity_with_behavior::<LoyaltyProgram, _>(LoyaltyProgramBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<LoyaltyProgram, _>::new(LoyaltyProgramChecker::default()))
        .entity_with_behavior::<ServiceCategory, _>(ServiceCategoryBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ServiceCategory, _>::new(ServiceCategoryChecker::default()))
        .entity_with_behavior::<ServiceCatalog, _>(ServiceCatalogBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ServiceCatalog, _>::new(ServiceCatalogChecker::default()))
        .entity_with_behavior::<BoxRental, _>(BoxRentalBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<BoxRental, _>::new(BoxRentalChecker::default()))
        .entity_with_behavior::<ServiceBundle, _>(ServiceBundleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ServiceBundle, _>::new(ServiceBundleChecker::default()))
        .entity_with_behavior::<CampaignStatus, _>(CampaignStatusBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<CampaignStatus, _>::new(CampaignStatusChecker::default()))
        .entity_with_behavior::<MarketingCampaign, _>(MarketingCampaignBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MarketingCampaign, _>::new(MarketingCampaignChecker::default()))
        .entity_with_behavior::<SalesLead, _>(SalesLeadBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<SalesLead, _>::new(SalesLeadChecker::default()))
        .entity_with_behavior::<PaymentMethod, _>(PaymentMethodBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<PaymentMethod, _>::new(PaymentMethodChecker::default()))
        .entity_with_behavior::<InvoiceDocument, _>(InvoiceDocumentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<InvoiceDocument, _>::new(InvoiceDocumentChecker::default()))
        .entity_with_behavior::<PaymentRecord, _>(PaymentRecordBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<PaymentRecord, _>::new(PaymentRecordChecker::default()))
        .entity_with_behavior::<ExpenseRecord, _>(ExpenseRecordBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ExpenseRecord, _>::new(ExpenseRecordChecker::default()))
        .entity_with_behavior::<VehicleType, _>(VehicleTypeBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<VehicleType, _>::new(VehicleTypeChecker::default()))
        .entity_with_behavior::<FleetVehicle, _>(FleetVehicleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<FleetVehicle, _>::new(FleetVehicleChecker::default()))
        .entity_with_behavior::<EquipmentItem, _>(EquipmentItemBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<EquipmentItem, _>::new(EquipmentItemChecker::default()))
        .entity_with_behavior::<MaintenanceSchedule, _>(MaintenanceScheduleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<MaintenanceSchedule, _>::new(MaintenanceScheduleChecker::default()))
        .entity_with_behavior::<FuelLog, _>(FuelLogBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<FuelLog, _>::new(FuelLogChecker::default()))
        .entity_with_behavior::<UserRole, _>(UserRoleBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<UserRole, _>::new(UserRoleChecker::default()))
        .entity_with_behavior::<NotificationType, _>(NotificationTypeBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<NotificationType, _>::new(NotificationTypeChecker::default()))
        .entity_with_behavior::<UserAccount, _>(UserAccountBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<UserAccount, _>::new(UserAccountChecker::default()))
        .entity_with_behavior::<RoleDefinition, _>(RoleDefinitionBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<RoleDefinition, _>::new(RoleDefinitionChecker::default()))
        .entity_with_behavior::<RoleAssignment, _>(RoleAssignmentBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<RoleAssignment, _>::new(RoleAssignmentChecker::default()))
        .entity_with_behavior::<AuditLog, _>(AuditLogBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<AuditLog, _>::new(AuditLogChecker::default()))
        .entity_with_behavior::<ServiceContract, _>(ServiceContractBehavior::default())
        .checker(teaql_runtime::TypedEntityChecker::<ServiceContract, _>::new(ServiceContractChecker::default()))
        .initial_graph(teaql_runtime::GraphNode::new("CompanyProfile")
            .value("id", 1_u64)
            .value("company_name", "SwiftMove Logistics")
            .value("registration_number", "REG-2020-001")
            .value("create_time", teaql_core::time::Timestamp::now())
            .value("update_time", teaql_core::time::Timestamp::now())
            .value("version", 1_i64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1001_u64)
            .value("name", "Scheduled")
            .value("code", "SCHEDULED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1002_u64)
            .value("name", "In Transit")
            .value("code", "IN_TRANSIT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1003_u64)
            .value("name", "Delivered")
            .value("code", "DELIVERED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("MoveStatus")
            .value("id", 1004_u64)
            .value("name", "Cancelled")
            .value("code", "CANCELLED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4001_u64)
            .value("name", "Driver")
            .value("code", "DRIVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4002_u64)
            .value("name", "Mover")
            .value("code", "MOVER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4003_u64)
            .value("name", "Dispatcher")
            .value("code", "DISPATCHER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("JobTitle")
            .value("id", 4004_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6001_u64)
            .value("name", "Private")
            .value("code", "PRIVATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CustomerType")
            .value("id", 6002_u64)
            .value("name", "Corporate")
            .value("code", "CORPORATE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8001_u64)
            .value("name", "Moving")
            .value("code", "MOVING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8002_u64)
            .value("name", "Cleaning")
            .value("code", "CLEANING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8003_u64)
            .value("name", "Packing")
            .value("code", "PACKING")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("ServiceCategory")
            .value("id", 8004_u64)
            .value("name", "Storage")
            .value("code", "STORAGE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9001_u64)
            .value("name", "Planned")
            .value("code", "PLANNED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9002_u64)
            .value("name", "Active")
            .value("code", "ACTIVE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("CampaignStatus")
            .value("id", 9003_u64)
            .value("name", "Completed")
            .value("code", "COMPLETED")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10001_u64)
            .value("name", "Credit Card")
            .value("code", "CREDIT_CARD")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10002_u64)
            .value("name", "Bank Transfer")
            .value("code", "BANK_TRANSFER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("PaymentMethod")
            .value("id", 10003_u64)
            .value("name", "Cash")
            .value("code", "CASH")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12001_u64)
            .value("name", "Small Van")
            .value("code", "SMALL_VAN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12002_u64)
            .value("name", "Medium Truck")
            .value("code", "MEDIUM_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("VehicleType")
            .value("id", 12003_u64)
            .value("name", "Large Truck")
            .value("code", "LARGE_TRUCK")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14001_u64)
            .value("name", "Administrator")
            .value("code", "ADMIN")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14002_u64)
            .value("name", "Manager")
            .value("code", "MANAGER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14003_u64)
            .value("name", "Employee")
            .value("code", "EMPLOYEE")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("UserRole")
            .value("id", 14004_u64)
            .value("name", "Customer")
            .value("code", "CUSTOMER")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15001_u64)
            .value("name", "Operational")
            .value("code", "OPERATIONAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15002_u64)
            .value("name", "Financial")
            .value("code", "FINANCIAL")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
        .initial_graph(teaql_runtime::GraphNode::new("NotificationType")
            .value("id", 15003_u64)
            .value("name", "Alert")
            .value("code", "ALERT")
            .value("version", 1_i64)
            .value("company_profile_id", 1_u64))
}