package com.doublechaintech.enterpriselogisticsservice;

import com.doublechaintech.enterpriselogisticsservice.accesspermission.AccessPermission;
import com.doublechaintech.enterpriselogisticsservice.corporatecustomer.CorporateCustomer;
import com.doublechaintech.enterpriselogisticsservice.discountcoupon.DiscountCoupon;
import com.doublechaintech.enterpriselogisticsservice.expenseitem.ExpenseItem;
import com.doublechaintech.enterpriselogisticsservice.field.Field;
import com.doublechaintech.enterpriselogisticsservice.insurancepolicy.InsurancePolicy;
import com.doublechaintech.enterpriselogisticsservice.pickupaddress.PickupAddress;
import com.doublechaintech.enterpriselogisticsservice.privatecustomer.PrivateCustomer;
import com.doublechaintech.enterpriselogisticsservice.promotioncampaign.PromotionCampaign;
import com.doublechaintech.enterpriselogisticsservice.safetytraining.SafetyTraining;
import com.doublechaintech.enterpriselogisticsservice.saleschannel.SalesChannel;
import com.doublechaintech.enterpriselogisticsservice.systemconfiguration.SystemConfiguration;
import com.doublechaintech.enterpriselogisticsservice.systemnotification.SystemNotification;
import com.doublechaintech.enterpriselogisticsservice.timeslot.TimeSlot;
import com.doublechaintech.enterpriselogisticsservice.transitroute.TransitRoute;
import com.doublechaintech.enterpriselogisticsservice.useraccount.UserAccount;
import com.doublechaintech.enterpriselogisticsservice.userrole.UserRole;
import com.doublechaintech.enterpriselogisticsservice.vehicle.Vehicle;
import com.doublechaintech.enterpriselogisticsservice.warehouse.Warehouse;
import com.doublechaintech.enterpriselogisticsservice.workshift.WorkShift;

public interface Constants  {
  public static final long FIELD_ID = 1l;
  public static final Field FIELD = Field.refer(FIELD_ID);
  public static final long TRANSIT_ROUTE_ID = 1l;
  public static final TransitRoute TRANSIT_ROUTE = TransitRoute.refer(TRANSIT_ROUTE_ID);
  public static final long TIME_SLOT_ID = 1l;
  public static final TimeSlot TIME_SLOT = TimeSlot.refer(TIME_SLOT_ID);
  public static final long PICKUP_ADDRESS_ID = 1l;
  public static final PickupAddress PICKUP_ADDRESS = PickupAddress.refer(PICKUP_ADDRESS_ID);
  public static final long VEHICLE_ID = 1l;
  public static final Vehicle VEHICLE = Vehicle.refer(VEHICLE_ID);
  public static final long WAREHOUSE_ID = 1l;
  public static final Warehouse WAREHOUSE = Warehouse.refer(WAREHOUSE_ID);
  public static final long WORK_SHIFT_ID = 1l;
  public static final WorkShift WORK_SHIFT = WorkShift.refer(WORK_SHIFT_ID);
  public static final long SAFETY_TRAINING_ID = 1l;
  public static final SafetyTraining SAFETY_TRAINING = SafetyTraining.refer(SAFETY_TRAINING_ID);
  public static final long PRIVATE_CUSTOMER_ID = 1l;
  public static final PrivateCustomer PRIVATE_CUSTOMER = PrivateCustomer.refer(PRIVATE_CUSTOMER_ID);
  public static final long CORPORATE_CUSTOMER_ID = 1l;
  public static final CorporateCustomer CORPORATE_CUSTOMER = CorporateCustomer.refer(CORPORATE_CUSTOMER_ID);
  public static final long PROMOTION_CAMPAIGN_ID = 1l;
  public static final PromotionCampaign PROMOTION_CAMPAIGN = PromotionCampaign.refer(PROMOTION_CAMPAIGN_ID);
  public static final long DISCOUNT_COUPON_ID = 1l;
  public static final DiscountCoupon DISCOUNT_COUPON = DiscountCoupon.refer(DISCOUNT_COUPON_ID);
  public static final long SALES_CHANNEL_ID = 1l;
  public static final SalesChannel SALES_CHANNEL = SalesChannel.refer(SALES_CHANNEL_ID);
  public static final long EXPENSE_ITEM_ID = 1l;
  public static final ExpenseItem EXPENSE_ITEM = ExpenseItem.refer(EXPENSE_ITEM_ID);
  public static final long INSURANCE_POLICY_ID = 1l;
  public static final InsurancePolicy INSURANCE_POLICY = InsurancePolicy.refer(INSURANCE_POLICY_ID);
  public static final long USER_ACCOUNT_ID = 1l;
  public static final UserAccount USER_ACCOUNT = UserAccount.refer(USER_ACCOUNT_ID);
  public static final long USER_ROLE_ID = 1l;
  public static final UserRole USER_ROLE = UserRole.refer(USER_ROLE_ID);
  public static final long ACCESS_PERMISSION_ID = 1l;
  public static final AccessPermission ACCESS_PERMISSION = AccessPermission.refer(ACCESS_PERMISSION_ID);
  public static final long SYSTEM_NOTIFICATION_ID = 1l;
  public static final SystemNotification SYSTEM_NOTIFICATION = SystemNotification.refer(SYSTEM_NOTIFICATION_ID);
  public static final long SYSTEM_CONFIGURATION_ID = 1l;
  public static final SystemConfiguration SYSTEM_CONFIGURATION = SystemConfiguration.refer(SYSTEM_CONFIGURATION_ID);
}