package com.doublechaintech.enterpriselogisticsservice;

import com.doublechaintech.enterpriselogisticsservice.auditlog.AuditLog;
import com.doublechaintech.enterpriselogisticsservice.claimsrecord.ClaimsRecord;
import com.doublechaintech.enterpriselogisticsservice.corporatecustomer.CorporateCustomer;
import com.doublechaintech.enterpriselogisticsservice.customsdeclaration.CustomsDeclaration;
import com.doublechaintech.enterpriselogisticsservice.discountcoupon.DiscountCoupon;
import com.doublechaintech.enterpriselogisticsservice.field.Field;
import com.doublechaintech.enterpriselogisticsservice.financialreport.FinancialReport;
import com.doublechaintech.enterpriselogisticsservice.insurancepolicy.InsurancePolicy;
import com.doublechaintech.enterpriselogisticsservice.privatecustomer.PrivateCustomer;
import com.doublechaintech.enterpriselogisticsservice.promotioncampaign.PromotionCampaign;
import com.doublechaintech.enterpriselogisticsservice.saleschannel.SalesChannel;
import com.doublechaintech.enterpriselogisticsservice.saleslead.SalesLead;
import com.doublechaintech.enterpriselogisticsservice.servicecontract.ServiceContract;
import com.doublechaintech.enterpriselogisticsservice.useraccount.UserAccount;
import com.doublechaintech.enterpriselogisticsservice.userrole.UserRole;
import com.doublechaintech.enterpriselogisticsservice.vehicle.Vehicle;
import com.doublechaintech.enterpriselogisticsservice.warehouse.Warehouse;
import com.doublechaintech.enterpriselogisticsservice.workshift.WorkShift;

public interface Constants  {
  public static final long FIELD_ID = 1l;
  public static final Field FIELD = Field.refer(FIELD_ID);
  public static final long VEHICLE_ID = 1l;
  public static final Vehicle VEHICLE = Vehicle.refer(VEHICLE_ID);
  public static final long WAREHOUSE_ID = 1l;
  public static final Warehouse WAREHOUSE = Warehouse.refer(WAREHOUSE_ID);
  public static final long WORK_SHIFT_ID = 1l;
  public static final WorkShift WORK_SHIFT = WorkShift.refer(WORK_SHIFT_ID);
  public static final long PRIVATE_CUSTOMER_ID = 1l;
  public static final PrivateCustomer PRIVATE_CUSTOMER = PrivateCustomer.refer(PRIVATE_CUSTOMER_ID);
  public static final long CORPORATE_CUSTOMER_ID = 1l;
  public static final CorporateCustomer CORPORATE_CUSTOMER = CorporateCustomer.refer(CORPORATE_CUSTOMER_ID);
  public static final long PROMOTION_CAMPAIGN_ID = 1l;
  public static final PromotionCampaign PROMOTION_CAMPAIGN = PromotionCampaign.refer(PROMOTION_CAMPAIGN_ID);
  public static final long DISCOUNT_COUPON_ID = 1l;
  public static final DiscountCoupon DISCOUNT_COUPON = DiscountCoupon.refer(DISCOUNT_COUPON_ID);
  public static final long SALES_LEAD_ID = 1l;
  public static final SalesLead SALES_LEAD = SalesLead.refer(SALES_LEAD_ID);
  public static final long SALES_CHANNEL_ID = 1l;
  public static final SalesChannel SALES_CHANNEL = SalesChannel.refer(SALES_CHANNEL_ID);
  public static final long FINANCIAL_REPORT_ID = 1l;
  public static final FinancialReport FINANCIAL_REPORT = FinancialReport.refer(FINANCIAL_REPORT_ID);
  public static final long SERVICE_CONTRACT_ID = 1l;
  public static final ServiceContract SERVICE_CONTRACT = ServiceContract.refer(SERVICE_CONTRACT_ID);
  public static final long INSURANCE_POLICY_ID = 1l;
  public static final InsurancePolicy INSURANCE_POLICY = InsurancePolicy.refer(INSURANCE_POLICY_ID);
  public static final long CLAIMS_RECORD_ID = 1l;
  public static final ClaimsRecord CLAIMS_RECORD = ClaimsRecord.refer(CLAIMS_RECORD_ID);
  public static final long CUSTOMS_DECLARATION_ID = 1l;
  public static final CustomsDeclaration CUSTOMS_DECLARATION = CustomsDeclaration.refer(CUSTOMS_DECLARATION_ID);
  public static final long AUDIT_LOG_ID = 1l;
  public static final AuditLog AUDIT_LOG = AuditLog.refer(AUDIT_LOG_ID);
  public static final long USER_ACCOUNT_ID = 1l;
  public static final UserAccount USER_ACCOUNT = UserAccount.refer(USER_ACCOUNT_ID);
  public static final long USER_ROLE_ID = 1l;
  public static final UserRole USER_ROLE = UserRole.refer(USER_ROLE_ID);
  public static final long USER_ROLE_ADMIN_ID = 1001l ;
  public static final UserRole USER_ROLE_ADMIN = UserRole.refer(USER_ROLE_ADMIN_ID);public static final long USER_ROLE_DISPATCHER_ID = 1002l ;
  public static final UserRole USER_ROLE_DISPATCHER = UserRole.refer(USER_ROLE_DISPATCHER_ID);public static final long USER_ROLE_DRIVER_ID = 1003l ;
  public static final UserRole USER_ROLE_DRIVER = UserRole.refer(USER_ROLE_DRIVER_ID);public static final long USER_ROLE_CS_ID = 1004l ;
  public static final UserRole USER_ROLE_CS = UserRole.refer(USER_ROLE_CS_ID);
}